version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: org.asciidoctor:asciidoctorj-diagram
      versions:
      - 2.1.1
      - 2.2.1
    - dependency-name: com.puppycrawl.tools:checkstyle
      versions:
        - ">= 10"
