categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'dependencies'
      - 'chore'
exclude-lables:
  - 'skip-changelog'
template: |
  ## What’s Changed

  $CHANGES
