= Demo
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
include::en/_common_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs
:toc: left

//image::{img}/

//tag::demo[]

== Celesta and Spring Boot

Demo project illustrating Celesta capabilities for Spring Boot is available at: https://github.com/inponomarev/celesta-demo/.

To create a Spring Boot project use the following Maven dependencies:

[source,xml]
----
    <properties>
       <!-- Check for the latest version of ru.curs:spring-boot-starter-web at Maven Central -->
       <spring.boot.starter.celesta.version>3.0.0</spring.boot.starter.celesta.version>
       <!-- Check for the latest version of ru.curs:celesta-parent at Maven Central -->
       <celesta.version>8.0.1</celesta.version>
    </properties>

. . .
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.curs</groupId>
            <!-- Own Spring Boot starter simplifies Celesta configuration in Spring Boot applications -->
            <artifactId>spring-boot-starter-celesta</artifactId>
            <version>${spring.boot.starter.celesta.version}</version>
            <!-- Exclude dependency on Celesta, specified in Celesta spring boot starter
                 to enter a more recent Celesta version number -->
            <exclusions>
                <exclusion>
                    <groupId>ru.curs</groupId>
                    <artifactId>celesta-system-services</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <!-- Connect a more recent version of Celesta than Spring Boot Starter propose-->
            <groupId>ru.curs</groupId>
            <artifactId>celesta-system-services</artifactId>
            <version>${celesta.version}</version>
        </dependency>
    ...
    </dependencies>
----

`ru.curs:celesta-maven-plugin` is used to generate the code of <<data_accessors_section,data access classes>>.
Specify the path to the `score` folder in its settings:

[source,xml]
----
    <build>
        <plugins>
            <plugin>
                <groupId>ru.curs</groupId>
                <artifactId>celesta-maven-plugin</artifactId>
                <version>${celesta.version}</version>

                <executions>
                    <execution>
                        <goals>
                            <goal>gen-cursors</goal>
                            <goal>gen-score-resources</goal>
                            <goal>gen-test-cursors</goal>
                            <goal>gen-test-score-resources</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
----

Add database definition scripts in <<CelestaSQL,CelestaSQL>> language to the `src/main/celestasql` folder.
For example,

[source,sql]
----
-- celestasql/ru/curs/demo/demo.sql
CREATE SCHEMA demo VERSION '1.0';

/**Order header*/
CREATE TABLE OrderHeader(
  id VARCHAR(30) NOT NULL,
  date DATETIME,
  customer_id VARCHAR(30),

  /**Costumer name */
  customer_name VARCHAR(50),
  manager_id VARCHAR(30),
  CONSTRAINT Pk_OrderHeader PRIMARY KEY (id)
);

/**Order line*/
CREATE TABLE OrderLine(
  order_id VARCHAR(30) NOT NULL,
  line_no INT NOT NULL,
  item_id VARCHAR(30) NOT NULL,
  item_name VARCHAR(100),
  qty INT NOT NULL DEFAULT 0,
  cost REAL NOT NULL DEFAULT 0.0,
  CONSTRAINT Idx_OrderLine PRIMARY KEY (order_id, line_no)
);

ALTER TABLE OrderLine ADD CONSTRAINT fk_OrderLine FOREIGN KEY (order_id) REFERENCES OrderHeader(id);
create materialized view OrderedQty as
select item_id, sum(qty) as qty from OrderLine group by item_id;
----

`mvn verify` command generates `OrderHeaderCursor.java`
 and `OrderLineCursor.java` files with <<data_accessors_section,cursor classes>> in the `target/generated-sources/celesta/...` folder.

Those classes can be used to create services (see the more comprehensive https://github.com/inponomarev/celesta-demo/blob/master/src/main/java/ru/curs/demo/service/DocumentService.java#L17[demo]):

[source,java]
----
@Service
public class DocumentService {
    @CelestaTransaction
    public void postOrder(CallContext context, OrderDto doc) {
        try (OrderHeaderCursor header = new OrderHeaderCursor(context);
             OrderLineCursor line = new OrderLineCursor(context)) {
             . . .
    }
}
----

Any https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html[method available in Spring Boot] can be used to configure your project's <<basic_settings_section,settings>>, including the https://github.com/inponomarev/celesta-demo/blob/master/src/main/resources/application.yml[application.yml] file.

== Using Celesta with Spring-JDBC

Celesta utilizes its own built-in JDBC connection pool if no other option is provided.
If you want to configure a specific connection pool, or if you want to utilize the https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[`DataSource`] provided by the Spring framework, you can do so. 

In standalone application you can use <<celesta_instantiation,`Celesta.createInstance`>> method providing a `DataSource` in its parameter.

`spring-boot-starter-celesta` will utilize a `DataSorce` when it is provided by Spring.

For example, if you add the following dependency:

[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-jdbc</artifactId>
</dependency>
----

and the following configuration parameters to `application.yml`

[source,yaml]
----
spring:
  datasource:
    url: jdbc:postgresql://<DATABASE>
    username: <USER>
    password: <PWD>
    hikari:
      auto-commit: false
celesta:
  jdbc:
    url: jdbc:postgresql
----

Celesta will run with https://github.com/brettwooldridge/HikariCP[Hikari Connection Pool] provided by Spring. Please note the following:

[IMPORTANT]
--
* The connection pool must be configured to return connections with `autoCommit` set to `false`.

* You still have to provide `celesta.jdbc.url` in order for Celesta to determine the type of the database, but since this parameter will not be used for connection to the database, it's enough to provide only the prefix, like `jdbc:postgresql`, `jdbc:sqlserver` etc.
--


//end::demo[] 


