= Celesta Configuration Parameters
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
include::en/_common_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs
:toc: left

//image::{img}/

//tag::basic_settings[]

Celesta configuration parameters include general system parameters such as database connection properties.

These settings are passed to a  {apidocs}ru/curs/celesta/BaseAppSettings.html[`BaseAppSettings`] constructor as a https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html[`Properties`] instance, and the `BaseAppSettings` instance, in turn, is a {apidocs}ru/curs/celesta/Celesta.html[`Celesta`] constructor parameter.

When using https://github.com/CourseOrchestra/spring-boot-starter-celesta[Celesta Spring Boot starter]
these settings are defined by any Spring Boot application https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html[configuration method] available, for example, using an
`application.yml` file.
In that case, the YAML file root key has to be `celesta`, and other properties are recorded in the hierarchical structure.

For example, to set the properties of `jdbc.url`, `jdbc.username` and `jdbc.password` the `application.yml` file structure must be the following:

```yaml
celesta:
  jdbc:
    url: jdbc:postgresql://127.0.0.1:5432/celesta
    # url: jdbc:sqlserver://172.16.1.114:52836;databaseName=celesta
    # url: jdbc:oracle:thin:192.168.110.128:1521:XE
    username: foo
    password: bar
```
Some IDE, like IntelliJ IDEA, provide auto-completion when editing the `application.yml` file.

[cols="30a,40a,^20a,^10a", options="header"]
|====
^.^|Parameter
^.^|Purpose
^.^|Mandatory
^.^|Default value

|`rdbms.connection.url`

(`jdbc.url` in `application.yml`)
|JDBC connection URL
|Yes
|-

|`rdbms.connection.username`

(`jdbc.username` in `application.yml`)
|Database login
|No (if empty, the JDBC URL is used)
|-

|`rdbms.connection.password`

(`jdbc.password` in `application.yml`)
|Database password
|No (if empty, the JDBC URL is used)
|-

|`skip.dbupdate`
|Forces the system to completely skip the database upgrade phase (including creating the system tables) on startup .

This parameter is required in some scenarios of deploying Celesta over an existing database.
|No
|`false`

|`force.dbinitialize`
|Forces the system to create Celesta system object even if the database is non-empty (contains tables) on startup.
Caution is advised when using this parameter because it may damage the existing database.

This parameter is required in some scenarios of deploying Celesta over an existing database.
|No
|`false`

|`h2.in-memory`
|`true` value forces Celesta to use an H2 database in in-memory mode.
JDBC connection parameters are ignored.
The mode is used mostly for automatic testing.
|No
|`false`

|`h2.port`
|When the value is an integer and `h2.in-memory` is set to `true`, the H2 database launches as a server at the specified port.
This mode allows external applications to connect to the H2 database and read and modify the data.
JDBC connection parameters are ignored.
The mode is used mostly for UI and acceptance automatic testing.
|No
|`false`

|`h2.referential.integrity`
|Defines the use of the foreign keys referential integrity checks, when working with an H2 database in in-memory mode (for all other databases this parameter is ignored).
By default the referential integrity checks are disabled when working with an H2 database in in-memory mode to simplify autotest creation.
|No
|`false`

|====

//end::basic_settings[]
