= Access Rights Granting and Change Logging
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs

//tag::security_logging[]

Working with data using data access classes not only allows to write universal code independent of RDBMS, but also to get around the issue of centralized granting the rights to access tables and log changes.

Calling some of the methods requires users to have corresponding permissions for tables, set in system tables `celesta.userroles` and `celesta.permissions`, otherwise an  {apidocs}ru/curs/celesta/PermissionDeniedException.html[`PermissionDeniedException`] exception occurs with a prompt "There is no ... permission for user ... on object ...".

If tables change logging is set up in the `celesta.logsetup` table, calling certain methods will result in creating entries in the `celesta.log` table.

[cols="1, 2, 4", options="header"]
|====
^.^|Method
^.^|Required permissions
^.^|Change logging

|`[try]first()`,
`[try]get()`,
`next()`.
|read permission (r)
|not logged

|`[try]insert()`
|insert permission (i)
a|logged if the "i" box is checked.

* `oldvalues` – empty value.

* `newvalues` – inserted entry.

|`[try]update()`
|modification permission (m)
a|logged if the "m" box is checked.

* `oldvalues` – entry value before modification.

* `newvalues` – entry value after modification.

|`delete[All]()`
|deletion permission (d)
a|`delete()` is logged if the "d" box is checked.

* `oldvalues` – entry value before deletion.

* `newvalues` – empty value.

|====

WARNING: `deleteAll()` is not logged and triggers are not executed.

Other methods do not require table access rights and calling them is not logged.
I.e. it is possible to define a cursor, set its filters and even count the number of entries meeting its conditions with a `count()` method without even a permission to read the table.

It is up to the developer to decide to use access rights granting mechanism.
If these methods are not used, their potential implementation results in a minimal performance overhead.

//end::security_logging[]
