= Dynamic Access to Data
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
include::en/_common_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs

//tag::dynamic[]

When writing universal data processing procedures (like export/import procedures) the issue of dynamic access to data arises in case the table/view/sequence name is known not at the stage of code writing but during execution.

To create a data access class instance when only a <<Celesta_metadata,score>> object is known, it is possible to use a static factory `create` method of the corresponding basic data access class, for example:

* {apidocs}ru/curs/celesta/dbutils/Cursor.html#create--[`Cursor.create(Table table, CallContext callContext)`]

* {apidocs}ru/curs/celesta/dbutils/ViewCursor.html#create--[`ViewCursor.create(View view, CallContext callContext)`]

* {apidocs}ru/curs/celesta/dbutils/Sequence.html#create--[`ViewCursor.create(SequenceElement sequence, CallContext callContext)`]

and so on.
`Cursor` and `ViewCursor` classes also have an overloaded version of the `create` method allowing to create data access object instances <<limit_columns,limited by set of columns>>.

Dynamic access to table cursor fields or representation in the `BasicCursor` class is performed using the following methods:

* {apidocs}ru/curs/celesta/dbutils/BasicCursor.html#getValue--[`BasicCursor.getValue(String name)`]

* {apidocs}ru/curs/celesta/dbutils/BasicCursor.html#setValue--[`BasicCursor.setValue(String name, Object value)`]


//end::dynamic[]
