= Triggers
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
include::en/_common_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs

//tag::triggers[]

Trigger is a function, which is written by the solution developer, accepts as arguments cursor instances attached to the cursor class and automatically called during entry insertion, deletion and modification.
Trigger looks like this: https://docs.oracle.com/javase/8/docs/api/index.html?java/util/function/Consumer.html[`Consumer<? super YourCursor>`].

When "insert()", "update()" or "delete()" actions are performed, the system calls certain solution developer-defined pre- and post-triggers (performed, respectively, before and after modifying the data in the database).
This means there are only six trigger types:

[cols="^1, ^1", options="header"]
|====
^.^|pre-triggers
^.^|post-triggers

|onPreInsert
|onPostInsert

|onPreUpdate
|onPostUpdate

|onPreDelete
|onPostDelete

|====

IMPORTANT: It often makes sense to use pre-triggers to perform certain action before the change is entered in the database.
Note that since "onPreInsert" trigger is executed before sending cursor contents to the database, values of fields possessing `DEFAULT` or `GETDATE()` properties are not filled in at the moment of its execution.
Assign a `null` value to them to automatically fill them in by the means of the database.
In the "onPostInsert" trigger these fields are already filled in.

It is convenient to use <<xrec_section,xRec objects>> in `onPreUpdate` triggers to determine exactly what fields are going to be modified in the table.
And in `onPreDelete` trigger it is impossible to use a xRec object because by that moment it becomes equal to the current buffer.

Tables may have any number of triggers of each type.
For every table triggers can be defined with *static* `onPreInsert`, `onPreDelete` and other methods on cursor classes.
Determining triggers with static methods makes them "global", i.e. they get executed at every interaction with the table.

Since the trigger registration method requires specifying the {apidocs}ru/curs/celesta/Celesta.html[`Celesta`] class instance, it is convenient to use `@PostConstruct` method to register triggers in Spring applications:

```java
@Service
public class MyService {

    @Autowired
    private ICelesta celesta;

    @PostConstruct
    public void init(){
        MyCursor.onPreInsert(celesta, c ->
                System.out.printf("Record %s is going to be inserted!%n", c.getId()));
    }

    . . .
}
```

The `MyCursor` code generated class has the following method:

```java
public static void onPreInsert(ICelesta celesta, Consumer<MyCursor> cursorConsumer)
```

System cursors (from the {apidocs}ru/curs/celesta/syscursors/package-summary.html[`ru.curs.celesta.syscursors`] packet) also support trigger registration.

//end::triggers[]
