= Celesta Score
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
include::en/_common_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs

//tag::meta[]

== Score and Dynamic Score Modification

A {apidocs}ru/curs/celesta/Celesta.html[`Celesta`] class instance is available with a *getCelesta()* method of a `{apidocs}ru/curs/celesta/CallContext.html[CallContext] context` variable sent as an argument to every data processing procedure.

The *getScore()* method provides the solution developer access to the system score built during parsing of CelestaSQL files.
Score access is necessary to receive information on current database structure when executing business logic code, including scores bound to database objects using <<CelestaDoc,CelestaDoc>>.

Score objects are not unchangeable, score current state can be uploaded in CelestaSQL using a {apidocs}ru/curs/celesta/score/GrainSaver.html[`GrainSaver`] class.

Score changeability may be used to develop tools that can read and generate CelestaSQL, for example, for integration with database visual design tools.
Changing the score when a programme runs that uses Celesta is not allowed and may cause non-determinate system behaviour.

== Score Composition

The ({apidocs}ru/curs/celesta/score/Score.html[`Score`]) score is divided into ({apidocs}ru/curs/celesta/score/Grain.html[`Grain`]) grains consisting of ({apidocs}ru/curs/celesta/score/Table.html[`Table`]) tables,  ({apidocs}ru/curs/celesta/score/Index.html[`Index`]) indices and ({apidocs}ru/curs/celesta/score/View.html[`View`]) views.

* Tables consist of ({apidocs}ru/curs/celesta/score/Column.html[`Column`]) columns and contain foreign keys.

* Indices belong to tables and contain their columns.

* Views contain ({apidocs}ru/curs/celesta/score/ViewColumnMeta.html[`ViewColumnMeta`]) view columns that differ from table columns, but share some properties with them.

Below a score description class diagram is presented.

include::../uml.adoc[tag="uml_metaclasses"]

The {apidocs}ru/curs/celesta/score/ColumnMeta.html[`ColumnMeta<V>`] interface is basic for table and view columns (`V` attribute corresponds to the Java type stored in the value column), which allows to determine the column data Celesta type, column nullability and <<CelestaDoc,CelestaDoc>> bound to it.
{apidocs}ru/curs/celesta/score/ViewColumnMeta.html[`ViewColumnMeta<V>`] classes implement this interface to describe fields, views and {apidocs}ru/curs/celesta/score/View.html[`Column<V>`] to describe table fields.

The `Column<V>` class is abstract and has subclasses for six field types supported in Celesta:

include::../uml.adoc[tag="uml_columnclasses"]

== Score Modification

Score modification is used only to develop CelestaSQL code generating tools.

WARNING: Score modification when a Celesta-based application is running may cause non-determinate system behaviour.

* To *create* new score objects constructors are used.
Some links to other elements are transferred in attributes, for example,  `IntegerColumn(table, name)` creates an integer field named `name` in the `table` field.

* To *remove* objects `delete()` methods are used defined in many score classes.

* Each {apidocs}ru/curs/celesta/score/NamedElement.html[`NamedElement`] inheriting class has `getCelestaDoc()` and `setCelestaDoc()` methods to read and install CelestaDoc documenting data.
CelestaDoc comments are saved when dynamically modified CelestaDoc score is saved to the file.

* See the corresponding  {apidocs}ru/curs/celesta/score/package-summary.html[API Documentation] for information on work with score objects.

//end::meta[]
