= CelestaUnit
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
include::en/_common_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs

//tag::celesta_unit[]

Usually, autotesting for data-modifying system poses certain difficulties and requires resorting to special techniques (like deploying database in a container).
Such tests are usually slow to perform and developers try to avoid them.


Testing data-editing methods in Celesta is performed at the level of fast unit tests and a https://junit.org/junit5/[JUnit5] extension is developed for it.
In Celesta, unit tests run on an embedded H2 database operating in an in-memory mode.
This database does not require installation, takes only a moment to start and vanishes after testing is complete.

Running a unit test under H2 is sufficient to ensure method correctness in production databases, because Celesta guarantees uniform data access class behaviour for all supported RDBMS (Celesta's own testing includes going through scenarios in real RDBMS).

To employ these functions, add a CelestaUnit Maven dependency:

```xml
<dependency>
    <groupId>ru.curs</groupId>
    <artifactId>celesta-unit<artifactId>
    <version>...</version>
    <scope>test</scope>
</dependency>
```

A JUnit5 dependency must also be added to the test scope of the project (see the https://junit.org/junit5/docs/current/user-guide/#dependency-metadata-junit-jupiter-samples[Junit5 Documentation] for examples).

== Usage Example

The easiest way to use it is to add a {apidocs}ru/curs/celestaunit/CelestaTest.html[`@CelestaTest`] annotation to the test class and use {apidocs}ru/curs/celesta/CallContext.html[`CallContext`] parameters in tests:

```java
/*CelestaTest annotation plugs in a JUnit5 extension class ru.curs.celestaunit.CelestaUnitExtension,
  allowing to use CallContext parameters in test methods.*/
@CelestaTest
public class DocumentServiceTest {

    /*Service can be created directly or using DI */

    DocumentService srv = new DocumentService();

    @Test
    /*CallContext parameter will be injected automatically
    based on a temporary H2 database*/
    void documentIsPutToDb(CallContext context) throws ParseException {
        /*Call the service*/
        srv.postOrder(context, ...);
        /*Check if the data got to the database*/
        OrderHeaderCursor header = new OrderHeaderCursor(context);
        header.tryFirst();
        assertEquals("no1", header.getId());
    }
}
```

This means every test can receive an active `CallContext` as a parameter.
This context is generated based on H2 database, to which a Celesta score is deployed and can be used to create cursors.

== Changing CelestaUnit Default Settings

CelestaUnit has the following defaults:

* score path: `src/main/resources/score`;
* reference integrity check (with foreign keys) is enabled;
* table clearing after each test is enabled.

Defaults can be changed by using a JUnit5 {apidocs}ru/curs/celestaunit/CelestaUnitExtension.html[`CelestaUnitExtension`] extension https://junit.org/junit5/docs/current/user-guide/#extensions-registration-programmatic[programmatic registration] in a test class:

```java
public class DocumentServiceTest {
    public static final String SCORE_PATH = "src/test/resources/score";
    @RegisterExtension
    static CelestaUnitExtension ext =
            CelestaUnitExtension.builder()
                    .withScorePath(SCORE_PATH)
                    .withReferentialIntegrity(true)
                    .withTruncateAfterEach(false).build();
```

In some cases it might help to disable reference integrity check to simplify adding test data to tables linked by foreign keys to other tables.

//end::celesta_unit[]
