= Best Practices in Celesta
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
include::en/_common_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs

//tag::best_practices[]

These advises help avoid some common mistakes when writing code to work with RDBMS using Celesta and describe some proven patterns.

== Close the Cursors Created in the Iteration Explicitly

Cursor is an object containing JDBC PreparedStatements and ResultSets necessary to execute cursor methods.
These resources must be closed after use.
Besides, the cursors and the objects constituting its inner state are not threadsafe, so the cursor must not be stored as a shared resource.
Cursor closing, loosing a link to it and transaction completion must normally happen simultaneously.

Cursor life cycle is limited to `CallContext` life cycle it was created with.
Calling `close()` on `CallContext` results in closing all cursors created in that context, so normally it is not necessary to explicitly close cursors in the code.

Still in some situations, when the cursor is created in an iteration, it must be closed explicitly.

CallContext <<too_many_accessors_warning,does not allow to create more than 1023 cursors>> (otherwise it throws an exception).
If a cursor can be created in an iteration, it must be closed (in the next point the code will be improved):

[cols="50a,50a",options=header]
|===
^| BAD
^| OK
|
[source,java]
----
@CelestaTransaction
void doSomething(CallContext context) {
  for (int i = 0; i < 2000; i++)
    doSomethingElse(context);
}

void doSomethingElse(CallContext context) {
  //Exception: too many data accessors
  FooCursor foo = new FooCursor (context);
}
----
|
[source,java]
----
@CelestaTransaction
void doSomething(CallContext context) {
  for (int i = 0; i < 2000; i++)
    doSomethingElse(context);
}

void doSomethingElse(CallContext context) {
  try(FooCursor foo = new FooCursor (context)){
  /*no exception thrown, but
  we can do better!*/
  }
}
----
|===

== Avoid Creating Cursors in Iterations

Opening and closing cursors in iterations results in multiple opening and closing JDBC PreparedStatements which is not optimal.
The best solution is to design code where cursors are created in the beginning of the service method and then reused:

[cols="50a,50a",options=header]
|===
^| OK
^| CORRECT
|
[source,java]
----
@CelestaTransaction
void doSomething(CallContext context) {
  for (int i = 0; i < 2000; i++)
    doSomethingElse(context);
}

void doSomethingElse(CallContext context) {
  try(FooCursor foo = new FooCursor (context)){
  /*no exception thrown, but
  we can do better!*/
  }
}
----
|
[source,java]
----
@CelestaTransaction
void doSomething(CallContext context) {
  FooCursor foo = new FooCursor (context);
  for (int i = 0; i < 2000; i++)
   doSomethingElse(foo);
}
void doSomethingElse(FooCursor foo) {
  /*now we do not create-and-close
  the cursor in each iteration*/
}
----
|===


== Limit the Set of the Columns Fetched by Cursor

If the table being read has many columns, but only some of them are worked with, <<limit_columns,define the needed columns explicitly>> to speed it up.
It can significantly reduce the amount of data transferred from the database.

== Methods not Addressing the Database are Fast

Cursor methods can be divided in three categories:

[cols="1a,1a,1a",options=header]
|===
|Not addressing the database
|Reading
|Updating

|
* setting / field reading
* `setRange`
* `setFilter`
* `setComplexFilter`
* `setIn`
* `limit`
* `orderBy`
* `reset`
* `clear`
|
* `[try]Get`
* `[try]First`
* `[try]Last`
* `[try]FindSet`
* `next`
* `navigate`
* `count`

|

* `[try]Insert`
* `[try]Update`
* `delete`
* `deleteAll`
|===

Calling methods of the first category does not result in sending any queries to the database.
For example, `orderBy` does not range entries at the moment the call happens, it only forms the cursor state to be used for forming SQL queries during the second and third category methods execution.

So the right pattern is to "prepare" the cursor as much as possible by setting all necessary limits using the first category methods before executing reading methods.


== Understand the `get(...)` Method Semantics

The `get(...)` method extracts a single record from the database by its known primary key.
It is a reliably fast (because the primary key always has an index) and the most demanded operation in practice.
The `get(...)` method _does not account for_ existence of any filters set for the cursor, so in rare cases when it is necessary to check if a record with a known key is in the range set by filters, a `navigate("=")` method must be used.

== Do not Read before Deleting if not Necessary

If the primary key of an entry for deletion is known, do not read it from the database using `get` or `find`.
Filling the primary key fields with correct values is enough for the `delete()` method.

[cols="50a,50a",options=header]
|===
^| WRONG
^| CORRECT
|

[source,java]
----
if (foo.tryGet(idForDeletion)) {
	foo.delete();
}
----
|
[source,java]
----
foo.setId(idForDeletion);
foo.delete();
----
|===

== Do not Use `count()` Only to Determine if the Data Range is not Empty

Common mistake is to check the range for emptiness using the `count()` method.
Counting all the records in the database only to determine if there are any at all is a bad idea.

[cols="50a,50a",options=header]
|===
^| WRONG
^| CORRECT
|

[source,java]
----
if (fooCursor.count() > 0) {
	...
}
----
|
[source,java]
----
if (fooCursor.tryFirst()) {
	...
}
----
|===


== Use Sorting at the Database Level to Find Min./Max. Values

If the search can be done in the database itself, better do that instead of sending the whole record set to the application to search using the application's resources:

[cols="50a,50a",options=header]
|===
| WRONG
| CORRECT
|

Iterating entries to find the maximum `bar` field value.

|
[source,java]
----
foo.orderBy(foo.COLUMNS.bar().desc());
foo.first();
----
|===


== Use the Correct Filter Type

There are four data filtering methods in Celesta, ranged from the simplest to the most complex:

. `setRange`
. `setFilter`
. `setComplexFilter`
. `setIn`

*Do not use more complex filters if the simpler one suffice!*

The <<set_range_usage,`setRange`>> method is applicable in most practical tasks to filter a field by a single value or a of range values:

* `cursor.setRange(cursor.COLUMNS.foo(), value)` creates a query in a `WHERE foo = value` format;
* `cursor.setRange(cursor.COLUMNS.foo(), from, to)` creates a query in a `WHERE foo BETWEEN from AND to` format.

[NOTE]
`cursor.setRange(cursor.COLUMNS.foo())` (no parameters) removes a filter for the `foo` field created earlier by `setRange` or `setFilter`.

The <<setFilter_usage,`setFilter`>> method is used in rare cases when a field value range to be filtered needs to be set as a complex expression.
A single field can have either a filter set by `setRange` or by `setFilter`, so calling these methods for the same field "replaces" the previously set filter.

`setRange` must be used whenever possible so Celesta can reuse JDBC `PreparedStatement` statements to greatly increase performance during the iteration:

[cols="50a,50a",options=header]
|===
^| WRONG
^| CORRECT
|

[source,java]
----
FooCursor foo = new FooCursor(context);
BarCursor bar = new BarCursor(context);
for (FooCursor c: foo){
  bar.setFilter("baz", "’"+c.getBaz()+"’");
  /* PreparedStatements are
  re-created in each iteration :-(( */
  ...
}

----
|
[source,java]
----
FooCursor foo = new FooCursor(context);
BarCursor bar = new BarCursor(context);
for (FooCursor c: foo){
  bar.setRange(“baz”, c.getBaz());
  /* PreparedStatement is created
  only once and is being reused :-)*/
}

----
|===

Also `setRange` is preferred because its API allows to control types sent as arguments for the method.

The <<set_complex_filter_usage,`setComplexFilter`>> method allows to add "a piece of SQL" to a `WHERE` expression setting the cursor entry set.
After any `setComplexFilter` call all JDBC `PreparedStatement` statements must be recreated, so as with `setFilter`, it is not efficient to call it in an iteration.
Main use for this method is to set conditions involving two or more fields, for example: `a >= b`.
In other cases `setRange`/`setFilter` should be used.


The <<setIn_usage,`setIn`>> method is instrumental in situations when the set of filtered values is determined dynamically from other data in the database.

== Use Indices

A general point for all RDBMS.
In Celesta, usually the following is true: if a `setRange` method is called for a cursor field, create an index for that field.

== Ensure Efficient Caching when Working in Iterations

Querying data in iterations is a common pattern.
It is possible to significantly reduce the number of queries to the database and increase speed by using the simplest caching: there is no need to call `get` for the cursor if the requested value of the primary key already matches the one requested earlier:

[source,java]
----
if (bar.getId() != c.getBarId())
		bar.get(c.getBarId());
//use newly fetched or cached bar here...
----

This idea can be developed in a very efficient pattern: it is possible to drastically reduce the number of queries for `bar` entries to the database by sorting the `c` cursor by the `barId` field:


[cols="50a,50a",options=header]
|===
^| WRONG
^| CORRECT
|

[source,java]
----
FooCursor foo = new FooCursor(context);
BarCursor bar = new BarCursor(context);
for (FooCursor c: foo){
  bar.get(c.getBarId());
/*fetching data
  in each iteration :-(*/
}


----
|
[source,java]
----
FooCursor foo = new FooCursor(context);
/*note the orderBy!!!*/
foo.orderBy(foo.COLUMNS.barId());
BarCursor bar = new BarCursor(context);
for (FooCursor c: foo){
  if (bar.getId() != c.getBarId())
	/*minimum number of fetches*/
	bar.get(c.getBarId());
}


----
|===

== Do not Use `try` Methods Unless Necessary

Many cursor methods have two versions: with and without a `try` prefix.
They act the same as far as processing speed is concerned, but from the perspective of code design (fail-fast approach) it is preferable to use methods without `try` if the returned Boolean value is not going to be used.
See this <<try_method_notice,explained in the documentation>>.

== Use Iteration instead of Navigation in Cycles

Two groups of methods exists to move between records in a cursor: navigation and iteration.

Navigation methods are `tryFirst()`, `next()`, `previous()` and `navigate(...)` which allow to move to a different record according to specific rules.

Iteration methods are a `tryFindSet()` – `nextInSet()` pair and an `iterator()` method implementing the respective `java.lang.Iterable` interface method.

Navigation methods send a query to the database per each call so they should be utilized when only a single entry is needed.

Iteration methods send queries and open JDBC `ResultSet` used for further movement between records.

[cols="50a,50a",options=header]
|===
^| WRONG
^| CORRECT
|

[source,java]
----
if (foo.tryFirst()){
  do {
     ...
  } while (foo.next());
  /*new query in each iteration :-(*/
}
----
|
[source,java]
----
/*only one query! :-)*/
for (FooCursor c: foo) {
  ...
}

----
|===

//end::best_practices[]