CREATE TABLE test(
  id INT NOT NULL IDENTITY,
  attrVarchar VARCHAR(2),
  attrInt INT DEFAULT 3,
  f1 BIT NOT NULL,
  f2 BIT DEFAULT 'TRUE',
  f4 REAL,
  f5 REAL NOT NULL DEFAULT 5.5,
  f6 TEXT NOT NULL DEFAULT 'abc',
  f7 VARCHAR(8),
  f8 DATETIME DEFAULT '20130401',
  f9 DATETIME NOT NULL DEFAULT GETDATE(),
  f10 BLOB DEFAULT 0xFFAAFFAAFF,
  f11 BLOB NOT NULL,
  CONSTRAINT pk_test PRIMARY KEY (id)
);

