CREATE GRAIN test VERSION '1.0';

CREATE table t1 (
  id INT NOT NULL,
  CONSTRAINT pk1 PRIMARY KEY (id)
) WITH READ ONLY;

CREATE table t2 (
  id INT NOT NULL,
  CONSTRAINT pk2 PRIMARY KEY (id)
) WITH NO VERSION CHECK;

CREATE table t3 (
  id INT NOT NULL,
  CONSTRAINT pk3 PRIMARY KEY (id)
) WITH NO AUTOUPDATE;

CREATE table t4 (
  id INT NOT NULL,
  CONSTRAINT pk PRIMARY KEY (id)
) WITH NO VERSION CHECK NO AUTOUPDATE;

CREATE table t5 (
  id INT NOT NULL,
  CONSTRAINT pk4 PRIMARY KEY (id)
) WITH VERSION CHECK;
