/* Generated By:JavaCC: Do not edit this line. CelestaParserConstants.java */
package ru.curs.celesta;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CelestaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_CREATE = 5;
  /** RegularExpression Id. */
  int K_TABLE = 6;
  /** RegularExpression Id. */
  int K_DEFAULT = 7;
  /** RegularExpression Id. */
  int K_NOT = 8;
  /** RegularExpression Id. */
  int K_NULL = 9;
  /** RegularExpression Id. */
  int K_MAX = 10;
  /** RegularExpression Id. */
  int K_INT = 11;
  /** RegularExpression Id. */
  int K_REAL = 12;
  /** RegularExpression Id. */
  int K_NVARCHAR = 13;
  /** RegularExpression Id. */
  int K_IMAGE = 14;
  /** RegularExpression Id. */
  int K_DATETIME = 15;
  /** RegularExpression Id. */
  int K_BIT = 16;
  /** RegularExpression Id. */
  int S_DOUBLE = 17;
  /** RegularExpression Id. */
  int S_INTEGER = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int S_BINARY_LITERAL = 20;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 21;
  /** RegularExpression Id. */
  int LETTER = 22;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 23;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 24;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 25;
  /** RegularExpression Id. */
  int LINE_COMMENT = 26;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"CREATE\"",
    "\"TABLE\"",
    "\"DEFAULT\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"MAX\"",
    "\"INT\"",
    "\"REAL\"",
    "\"NVARCHAR\"",
    "\"IMAGE\"",
    "\"DATETIME\"",
    "\"BIT\"",
    "<S_DOUBLE>",
    "<S_INTEGER>",
    "<DIGIT>",
    "<S_BINARY_LITERAL>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\";\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"-\"",
  };

}
