/* Generated By:JavaCC: Do not edit this line. CelestaParserConstants.java */
package ru.curs.celesta;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CelestaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_CREATE = 5;
  /** RegularExpression Id. */
  int K_TABLE = 6;
  /** RegularExpression Id. */
  int K_INDEX = 7;
  /** RegularExpression Id. */
  int K_DEFAULT = 8;
  /** RegularExpression Id. */
  int K_NOT = 9;
  /** RegularExpression Id. */
  int K_NULL = 10;
  /** RegularExpression Id. */
  int K_MAX = 11;
  /** RegularExpression Id. */
  int K_IDENTITY = 12;
  /** RegularExpression Id. */
  int K_GETDATE = 13;
  /** RegularExpression Id. */
  int K_PRIMARY = 14;
  /** RegularExpression Id. */
  int K_FOREIGN = 15;
  /** RegularExpression Id. */
  int K_KEY = 16;
  /** RegularExpression Id. */
  int K_REFERENCES = 17;
  /** RegularExpression Id. */
  int K_ON = 18;
  /** RegularExpression Id. */
  int K_UPDATE = 19;
  /** RegularExpression Id. */
  int K_DELETE = 20;
  /** RegularExpression Id. */
  int K_NO = 21;
  /** RegularExpression Id. */
  int K_ACTION = 22;
  /** RegularExpression Id. */
  int K_SET = 23;
  /** RegularExpression Id. */
  int K_CASCADE = 24;
  /** RegularExpression Id. */
  int K_INT = 25;
  /** RegularExpression Id. */
  int K_REAL = 26;
  /** RegularExpression Id. */
  int K_NVARCHAR = 27;
  /** RegularExpression Id. */
  int K_IMAGE = 28;
  /** RegularExpression Id. */
  int K_DATETIME = 29;
  /** RegularExpression Id. */
  int K_BIT = 30;
  /** RegularExpression Id. */
  int S_DOUBLE = 31;
  /** RegularExpression Id. */
  int S_INTEGER = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;
  /** RegularExpression Id. */
  int S_BINARY_LITERAL = 34;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 35;
  /** RegularExpression Id. */
  int LETTER = 36;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 37;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 38;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 39;
  /** RegularExpression Id. */
  int LINE_COMMENT = 40;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"CREATE\"",
    "\"TABLE\"",
    "\"INDEX\"",
    "\"DEFAULT\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"MAX\"",
    "\"IDENTITY\"",
    "\"GETDATE\"",
    "\"PRIMARY\"",
    "\"FOREIGN\"",
    "\"KEY\"",
    "\"REFERENCES\"",
    "\"ON\"",
    "\"UPDATE\"",
    "\"DELETE\"",
    "\"NO\"",
    "\"ACTION\"",
    "\"SET\"",
    "\"CASCADE\"",
    "\"INT\"",
    "\"REAL\"",
    "\"NVARCHAR\"",
    "\"IMAGE\"",
    "\"DATETIME\"",
    "\"BIT\"",
    "<S_DOUBLE>",
    "<S_INTEGER>",
    "<DIGIT>",
    "<S_BINARY_LITERAL>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\";\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"-\"",
  };

}
