= Демонстрационный пример
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
include::ru/_common_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs
:toc: left

//image::{img}/

//tag::demo[]

Тестовый пример, демонстрирующий возможности Celesta в проекте на основе Spring Boot, доступен здесь: https://github.com/inponomarev/celesta-demo/.

Для создания проекта Spring Boot с помощью Maven необходимо указать следующие зависимости:

```xml
    <properties>
       <!-- Проверьте свежую версию ru.curs:spring-boot-starter-web на Maven Central -->
       <spring.boot.starter.celesta.version>2.1.7</spring.boot.starter.celesta.version>
       <!-- Проверьте свежую версию ru.curs:celesta-parent на Maven Central -->
       <celesta.version>7.2.5</celesta.version>
    </properties>

. . .
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.curs</groupId>
            <!-- Собственный Spring Boot starter облегчает конфигурацию Celesta в Spring Boot приложениях -->
            <artifactId>spring-boot-starter-celesta</artifactId>
            <version>${spring.boot.starter.celesta.version}</version>
            <!-- Исключаем зависимость от Celesta, указанную в Celesta spring boot starter,
                 чтобы ниже указать более актуальный номер версии Celesta -->
            <exclusions>
                <exclusion>
                    <groupId>ru.curs</groupId>
                    <artifactId>celesta-system-services</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <!-- Подключаем Celesta более свежей версии, чем предлагает Spring Boot Starter-->
            <groupId>ru.curs</groupId>
            <artifactId>celesta-system-services</artifactId>
            <version>${celesta.version}</version>
        </dependency>
    ...
    </dependencies>
```

Также для кодогенерации <<data_accessors_section,классов доступа к данным>> понадобится `ru.curs:celesta-maven-plugin`.
В его настройках необходимо указать путь к папке `score`:

```xml
    <build>
        <plugins>
            <plugin>
                <groupId>ru.curs</groupId>
                <artifactId>celesta-maven-plugin</artifactId>
                <version>${celesta.version}</version>

                <executions>
                    <execution>
                        <goals>
                            <goal>gen-cursors</goal>
                            <goal>gen-score-resources</goal>
                            <goal>gen-test-cursors</goal>
                            <goal>gen-test-score-resources</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

В папке `src/main/celestasql` следует разместить скрипты определения базы данных на языке <<CelestaSQL,CelestaSQL>>.
Например,

```sql
-- celestasql/ru/curs/demo/demo.sql
CREATE SCHEMA demo VERSION '1.0';

/**Заголовок счёта*/
CREATE TABLE OrderHeader(
  id VARCHAR(30) NOT NULL,
  date DATETIME,
  customer_id VARCHAR(30),

  /**Название клиента */
  customer_name VARCHAR(50),
  manager_id VARCHAR(30),
  CONSTRAINT Pk_OrderHeader PRIMARY KEY (id)
);

/**Строка счёта*/
CREATE TABLE OrderLine(
  order_id VARCHAR(30) NOT NULL,
  line_no INT NOT NULL,
  item_id VARCHAR(30) NOT NULL,
  item_name VARCHAR(100),
  qty INT NOT NULL DEFAULT 0,
  cost REAL NOT NULL DEFAULT 0.0,
  CONSTRAINT Idx_OrderLine PRIMARY KEY (order_id, line_no)
);

ALTER TABLE OrderLine ADD CONSTRAINT fk_OrderLine FOREIGN KEY (order_id) REFERENCES OrderHeader(id);
create materialized view OrderedQty as
select item_id, sum(qty) as qty from OrderLine group by item_id;
```

Команда `mvn verify` приведёт к появлению Java-файлов `OrderHeaderCursor.java`
 и `OrderLineCursor.java` с <<data_accessors_section,классами курсоров>> в папке  `target/generated-sources/celesta/...`.

Эти классы можно использовать при создании сервисов (см. также более полный https://github.com/inponomarev/celesta-demo/blob/master/src/main/java/ru/curs/demo/service/DocumentService.java#L17[демонстрационный пример]):

```java
@Service
public class DocumentService {
    @CelestaTransaction
    public void postOrder(CallContext context, OrderDto doc) {
        try (OrderHeaderCursor header = new OrderHeaderCursor(context);
             OrderLineCursor line = new OrderLineCursor(context)) {
             . . .
    }
}
```

Управление <<basic_settings_section,настройками>> проекта осуществляется любым https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html[доступным для Spring Boot способом], в частности, с помощью файла https://github.com/inponomarev/celesta-demo/blob/master/src/main/resources/application.yml[application.yml].
//end::demo[]
