= Maven-плагин
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
include::ru/_common_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs
:toc: left

//image::{img}/

//tag::maven_plugin[]

Celesta-maven-plugin осуществляет кодогенерацию классов доступа к данным на основе CelestaSQL-скриптов.
Подключение этого плагина обязательно для проектов, использующих Celesta.

Пример использования:

```xml
<plugin>
    <groupId>ru.curs</groupId>
    <artifactId>celesta-maven-plugin</artifactId>
    <version>${celesta.version}</version>
    <configuration>
        <scores>
            <score>. . .</score>
        </scores>
        <testScores>
            <testScore>. . .</testScore>
        </testScores>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>gen-cursors</goal>
                <goal>gen-score-resources</goal>
                <goal>gen-test-cursors</goal>
                <goal>gen-test-score-resources</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Параметры конфигурации плагина:

* `scores` — пути к папкам в проекте, где размещены <<CelestaSQL>>-скрипты, описывающие рабочую базу данных.
По умолчанию содержит путь `src/main/celestasql`.
* `testScores` — пути к папкам в проекте, где размещены <<CelestaSQL>>-скрипты, описывающие базу данных, используемую только для <<celestaunit_section,модульного тестирования>>.
По умолчанию содержит путь `src/test/celestasql`.

Celesta Maven Plugin производит следующие операции:

1. Кодогенерирует <<data_accessors_section,курсоры>> на основе <<CelestaSQL>>:

** На фазе `generate-sources` происходит кодогенерация курсоров из `scores` и опционально папки `score` в `target/generated-sources/celesta`,

** На фазе `generate-test-sources` -- из `testScores` в `target/generated-test-sources/celesta`.

2. Копирует CelestaSQL файлы в ресурсы:

** На фазе `generate-resources` происходит копирование файлов CelestaSQL из `scores` и опционально папки `score` в `generated-resources/score`

** На фазе `generate-test-resources` -- из `testScores` в `generated-test-resources/score`

3. Генерирует индекс `score.files` с перечнем относительных путей к .sql-файлам в ресурсах:

** На фазе `generate-resources` -> `generated-resources/score/score.files`
** На фазе `generate-test-resources` ->`generated-test-resources/score/score.files`

Эти файлы используются во время выполнения Celesta для того, чтобы найти пути ко всем CelestaSQL-файлам внутри jar-файлов на classpath.

//end::maven_plugin[]
