= Параметры конфигурации Celesta
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs
:toc: left

//image::{img}/

//tag::basic_settings[]

К параметрам конфигурации Celesta относятся общесистемные параметры, такие как параметры подключения к базе данных.

Эти настройки в виде экземпляра https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html[`Properties`] передаются в конструктор класса {apidocs}ru/curs/celesta/BaseAppSettings.html[`BaseAppSettings`], который,
в свою очередь, является параметром конструктора класса {apidocs}ru/curs/celesta/Celesta.html[`Celesta`].

При использовании https://github.com/CourseOrchestra/spring-boot-starter-celesta[Celesta Spring Boot starter]
эти настройки транслируются через конфигурацию любым из способов https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html[способов конфигурации] Spring Boot приложений, например, через файл
`application.yml`.
В последнем случае корневым ключом YAML-файла должен быть `celesta`, а остальные свойства записываются в иерархической структуре.

Например, для задания свойств `jdbc.url`, `jdbc.username` и `jdbc.password` структура файла `application.yml` будет следующей:

```yaml
celesta:
  jdbc:
    url: jdbc:postgresql://127.0.0.1:5432/celesta
    # url: jdbc:sqlserver://172.16.1.114:52836;databaseName=celesta
    # url: jdbc:oracle:thin:192.168.110.128:1521:XE
    username: foo
    password: bar
```
Некоторые IDE, например, IntelliJ IDEA, выполняют контекстную подсказку при редактировании файла `application.yml`.

[cols="30a,40a,^20a,^10a", options="header"]
|====
^.^|Параметр
^.^|Назначение
^.^|Обязательный
^.^|Значение по умолчанию

|`rdbms.connection.url`

(`jdbc.url` в `application.yml`)
|URL подключения к JDBC-драйверу
|Да
|-

|`rdbms.connection.username`

(`jdbc.username` в `application.yml`)
|Логин для подключения к базе данных
|Нет (если не заполнен, используется информация из JDBC URL)
|-

|`rdbms.connection.password`

(`jdbc.password` в `application.yml`)
|Пароль для подключения к базе данных
|Нет (если не заполнен, используется информация из JDBC URL)
|-

|`skip.dbupdate`
|Заставляет систему при инициализации полностью пропустить фазу обновления базы данных (включая создание системных таблиц).

Этот параметр требуется при некоторых сценариях разворачивания Celesta на заранее существующей базе данных.
|Нет
|`false`

|`force.dbinitialize`
|Заставляет систему при инициализации создавать системные объекты Celesta даже в том случае, если база данных не пустая (уже содержит таблицы).
Этот параметр рекомендуется использовать с осторожностью, чтобы не повредить существующую базу данных.

Этот параметр требуется при некоторых сценариях разворачивания Celesta на заранее существующей базе данных.
|Нет
|`false`

|`h2.in-memory`
|Значение `true` заставляет Celesta использовать базу H2 в in-memory режиме.
Параметры JDBC подключения при этом игнорируются.
Режим необходим, прежде всего, для автоматических тестов.
|Нет
|`false`

|`h2.port`
|Если указано целочисленное значение, и при этом `h2.in-memory` установлено в `true`, то база H2 запускается в виде сервера на указанном порту.
Данный режим позволяет присоединяться к базе данных H2 внешним приложениям, читать и модифицировать данные.
Параметры JDBC подключения при этом игнорируются.
Этот режим необходим для UI и приёмочных автоматических тестов.
|Нет
|`false`

|`h2.referential.integrity`
|Использовать ли контроль ссылочной целостности (контроль Foreign Keys), работая с базой H2 в in-memory режиме (для всех других БД данный параметр игнорируется).
По умолчанию при работе с H2 in-memory, ссылочная целостность отключается для упрощения создания автоматических тестов.
|Нет
|`false`

|====

//end::basic_settings[]
