= Распределение прав доступа и протоколирование изменений
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
include::ru/_common_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs

//tag::security_logging[]

Работа с данными через классы доступа к данным даёт не только возможность писать универсальный, не зависящий от используемой СУБД код, но также и решить задачу централизованного распределения прав доступа к данным таблиц и протоколирования изменений.

Вызов ряда методов требует наличия соответствующих прав у пользователя на таблицы, прописанных в системных таблицах `celesta.userroles` и `celesta.permissions`, в противном случае возникает исключение {apidocs}ru/curs/celesta/PermissionDeniedException.html[`PermissionDeniedException`] с сообщением вида "There is no ... permission for user ... on object ...".

Если протоколирование изменения таблицы настроено в таблице `celesta.logsetup`, то вызов некоторых методов будет приводить к созданиям записей в таблице `celesta.log`.

[cols="1, 2, 4", options="header"]
|====
^.^|Метод
^.^|Требуемые права
^.^|Протоколирование изменений

|`[try]first()`,
`[try]get()`,
`next()`.
|на чтение (r)
|не протоколируются

|`[try]insert()`
|на вставку (i)
a|протоколируется, если включён флаг i.

* `oldvalues` -- пустое значение.

* `newvalues` -- вставляемая запись.

|`[try]update()`
|на модификацию (m)
a|протоколируется, если включён флаг m.

* `oldvalues` -- состояние записи до модификации.

* `newvalues` -- состояние записи после модификации.

|`delete[All]()`
|на удаление (d)
a|`delete()` протоколируется, если включён флаг d.

* `oldvalues` -- состояние записи до удаление.

* `newvalues` -- пустое значение.

|====

WARNING: `deleteAll()` не протоколируется и триггеры не выполняются.

Прочие методы не требуют никаких прав доступа к таблице и вызов их не протоколируется.
Т. е. определить курсор, выставить на нём фильтры и даже подсчитать количество подпадающих под фильтры записей при помощи метода `count()` можно, даже не имея никаких прав на чтение таблицы.

Механизмом распределения прав и протоколирования можно как пользоваться, так и не пользоваться.
При этом, если ими не пользоваться, их потенциальное наличие создаёт минимальный overhead по производительности.

//end::security_logging[]
