== Динамический доступ к данным
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs

//tag::dynamic[]

При написании универсальных процедур обработки данных (таких, например, как процедуры экспорта/импорта) зачастую возникает задача динамического доступа к данным, когда название таблицы/представления/последовательности известно не на этапе написания кода, а во время выполнения.

Чтобы создать экземпляр класса доступа к данным, зная лишь объект <<Celesta_metadata,метаданных>>, можно воспользоваться фабричным статическим методом `create`  соответствующего базового класса доступа к данным, например:

* {apidocs}ru/curs/celesta/dbutils/Cursor.html#create--[`Cursor.create(Table table, CallContext callContext)`]

* {apidocs}ru/curs/celesta/dbutils/ViewCursor.html#create--[`ViewCursor.create(View view, CallContext callContext)`]

* {apidocs}ru/curs/celesta/dbutils/Sequence.html#create--[`ViewCursor.create(SequenceElement sequence, CallContext callContext)`]

и так далее.
У классов `Cursor` и `ViewCursor` имеется также перегруженная версия метода `create`, позволяющая создавать экземпляры объектов доступа к данным с <<limit_columns,ограничением по выборке столбцов>>.

Для динамического доступа к значениям полей курсора таблицы или представления в классе `BasicCursor` предусмотрены методы

* {apidocs}ru/curs/celesta/dbutils/BasicCursor.html#getValue--[`BasicCursor.getValue(String name)`]

* {apidocs}ru/curs/celesta/dbutils/BasicCursor.html#setValue--[`BasicCursor.setValue(String name, Object value)`]


//end::dynamic[]
