= Объект xRec
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
include::ru/_common_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs

//tag::xrec[]

Объект `xRec`, получаемый с помощью метода `getXRec()`, предназначен преимущественно для использования в <<triggers_section,триггере>> `onPreUpdate`.
Сравнивая поля `xRec` с текущими значениями полей, можно определить, что именно изменилось в записи.

`xRec` хранит значения полей, полученные при последнем чтении курсора из базы данных (в отличие от основного буфера, поля которого после чтения равны полям `xRec`, но затем изменяются, когда пользователь присваивает им новые значения).
Обновление объекта `xRec` происходит только при следующих действиях:

* `[try]first()`,

* `[try]get()`,

* `next()`,

* `[try]insert()` (по сути после вставки система выполняет операцию `get()` для курсора, чтобы прочитать значения, выданные базой данных на поля `IDENITY`, `GETDATE()`, `DEFAULT`, обновляя и основной буфер, и `xRec`),

* `[try]update()` (после обновления в БД xRec становится копией текущего курсора),

* `delete()` (после обновления в БД xRec заполняется значением буфера, как он был до удаления).

Обратите внимание, что в pre- и post- триггерах значение `xRec` будет различным!


//end::xrec[]
