= Метаданные Celesta
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs

//tag::meta[]

== Метаданные и их динамическое изменение

Экземпляр класса {apidocs}ru/curs/celesta/Celesta.html[`Celesta`] доступен через метод *getCelesta()* переменной `{apidocs}ru/curs/celesta/CallContext.html[CallContext] context`, передаваемой в качестве аргумента в каждую процедуру обработки данных.

Через метод *getScore()* экземпляра класса Celesta разработчик решения может получить доступ к метаданным системы, построенным при разборе CelestaSQL-файлов.
Доступ к метаданным необходим для получения информации о текущей структуре базы данных во время выполнения кода бизнес-логики, в том числе дополнительных метаданных, привязанных к объектами базы данных через <<CelestaDoc,CelestaDoc>>.

Объекты метаданных не являются неизменяемыми, текущее состояние метаданных может быть выгружено в CelestaSQL с помощью класса {apidocs}ru/curs/celesta/score/GrainSaver.html[`GrainSaver`].

Изменяемость метаданных можно использовать для разработки инструментов, читающих и генерирующих CelestaSQL -- например, для интеграции с инструментами визуального проектирования баз данных.
Изменение метаданных во время выполнения программы, использующей Celesta, запрещено и может привести к недетерминированному поведению системы.

== Состав метаданных

Все метаданные ({apidocs}ru/curs/celesta/score/Score.html[`Score`]) делятся на гранулы ({apidocs}ru/curs/celesta/score/Grain.html[`Grain`]), состоящие из таблиц ({apidocs}ru/curs/celesta/score/Table.html[`Table`]), индексов ({apidocs}ru/curs/celesta/score/Index.html[`Index`]) и представлений ({apidocs}ru/curs/celesta/score/View.html[`View`]).

* Таблицы состоят из столбцов ({apidocs}ru/curs/celesta/score/Column.html[`Column`]) и содержат внешние ключи.

* Индексы относятся к таблицам и состоят из их столбцов (Column).

* Представления состоят из столбцов представлений ({apidocs}ru/curs/celesta/score/ViewColumnMeta.html[`ViewColumnMeta`]), которые отличаются от столбцов таблиц, но имеют ряд общих свойств.

Ниже представлена диаграмма классов, описывающих метаданные.

include::../uml.adoc[tag="uml_metaclasses"]

Базовым интерфейсом для столбцов таблиц и представлений является интерфейс {apidocs}ru/curs/celesta/score/ColumnMeta.html[`ColumnMeta<V>`] (параметр `V` соответствует Java-типу хранимого в столбце значения), с помощью которого можно узнать Celesta-тип данных столбца, его nullability и <<CelestaDoc,CelestaDoc>>, привязанный к данному столбцу.
Данный интерфейс реализуют классы {apidocs}ru/curs/celesta/score/ViewColumnMeta.html[`ViewColumnMeta<V>`] для описания полей представлений и {apidocs}ru/curs/celesta/score/View.html[`Column<V>`] для описания полей таблиц.

Класс `Column<V>` является абстрактным, и для шести типов полей, поддерживаемых Celesta, от него наследуются шесть субклассов:

include::../uml.adoc[tag="uml_columnclasses"]

== Модификация метаданных

Модификация метаданных используется только при разработке инструментов, генерирующих CelestaSQL код.

WARNING: Модификация метаданных во время выполнения приложения на базе Celesta может привести к недетерминированному поведению системы.

* Для *создания* новых объектов метаданных используются конструкторы.
Необходимые связи с другими элементами передаются через параметры: например, `IntegerColumn(table, name)` создаёт новое целочисленное поле с именем `name` в таблице `table`.

* Для *удаления* объектов следует пользоваться методами `delete()`, определёнными во многих из классов метаданных.

* У каждого класса-наследника {apidocs}ru/curs/celesta/score/NamedElement.html[`NamedElement`] имеются методы `getCelestaDoc()` и `setCelestaDoc()` для чтения и установки документирующих данных CelestaDoc.
При сохранении в файл динамически изменённых метаданных CelestaDoc-комментарии сохраняются.

* Для работы с объектами метаданных см. соответствующую {apidocs}ru/curs/celesta/score/package-summary.html[документацию по API].

//end::meta[]
