create grain sequences version '1.0';

CREATE SEQUENCE s1;

--TEST START WITH
CREATE SEQUENCE s2 START WITH 3;

--TEST INCREMENT
CREATE SEQUENCE s3 INCREMENT BY 2;
/* MAXVALUE IS REQUIRED ON DESC ORDERING */
CREATE SEQUENCE s4 INCREMENT BY -2 MINVALUE -99999999 MAXVALUE 1;
CREATE SEQUENCE s5 START WITH 5 INCREMENT BY - 1 MINVALUE -99999999 MAXVALUE 5;
CREATE SEQUENCE s6 START WITH 5 MINVALUE 4 INCREMENT BY -1 MAXVALUE 6;
CREATE SEQUENCE s7 START WITH -3 MINVALUE -6 INCREMENT BY -2 MAXVALUE -3;
CREATE SEQUENCE s8 START WITH -1 INCREMENT BY -2 MINVALUE -1 MAXVALUE 2;

--TEST MINVALUE
CREATE SEQUENCE s9 START WITH 5 MINVALUE 5;
CREATE SEQUENCE s10 START WITH -5 MINVALUE -5;

CREATE SEQUENCE s11 MAXVALUE 56;
CREATE SEQUENCE s12 CYCLE  MAXVALUE 5;
CREATE SEQUENCE s13 INCREMENT BY -1 CYCLE MINVALUE -1 MAXVALUE 1;
CREATE SEQUENCE s14 START WITH 5 INCREMENT BY 2 MINVALUE 5 MAXVALUE 56 CYCLE;
CREATE SEQUENCE s15 START WITH 5 CYCLE MAXVALUE 56 INCREMENT BY 2 MINVALUE 5;

CREATE SEQUENCE t1_sequence START WITH 4 INCREMENT BY 2;

CREATE TABLE t1(
  id int DEFAULT NEXTVAL(t1_sequence) not null,
  CONSTRAINT Pk_sequences_t1 PRIMARY KEY (id)
);