/* Generated By:JavaCC: Do not edit this line. FilterParserConstants.java */
package ru.curs.celesta.dbutils.filter;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FilterParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int S_DOUBLE = 2;
  /** RegularExpression Id. */
  int S_INTEGER = 3;
  /** RegularExpression Id. */
  int DIGIT = 4;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 5;
  /** RegularExpression Id. */
  int S_NULL = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<S_DOUBLE>",
    "<S_INTEGER>",
    "<DIGIT>",
    "<S_CHAR_LITERAL>",
    "\"NULL\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\">\"",
    "\"<\"",
    "\"..\"",
    "\"@\"",
    "\"%\"",
  };

}
