= Язык Celesta-SQL
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs
//tag::celesta_sql[]

== Язык CelestaSQL определения объектов базы данных

WARNING: Скрипты на языке CelestaSQL должны иметь кодировку UTF-8 без https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8[символа BOM].

На языке Celesta SQL пишутся скрипты определения гранул. Скрипт на языке CelestaSQL состоит из конструкций

* <<create_schema_statement,CREATE GRAIN>>,
* <<create_sequence_statement,CREATE SEQUENCE>>,
* <<create_table_statement,CREATE TABLE>>,
* <<foreign_keys_statements,ALTER TABLE ... ADD FOREIGN KEY>>,
* <<create_index_statement,CREATE INDEX>>,
* <<create_view_statement,CREATE VIEW>>,
* <<create_materialized_view_statement,CREATE MATERIALIZED VIEW>>,
* <<create_function_statement,CREATE FUNCTION>>,

в обязательном порядке разделённых точкой с запятой, начиная с `CREATE GRAIN`:


[syntrax,script,svg,opts=interactive]   
....
line('/create_grain', loop(';', 
    choice('/create_sequence',
           '/create_table',
           '/add_foreign_key',
           '/create_index',
           '/create_view',
           '/create_materialized_view',
           '/create_function'))
)

url_map = {
  'create_grain': '.#create_grain',
  'create_sequence': '.#create_sequence',
  'create_table': '.#create_table',
  'add_foreign_key': '.#add_foreign_key',
  'create_index': '.#create_index',
  'create_view': '.#create_view',
  'create_materialized_view': '.#create_materialized_view',
  'create_function': '.#create_function'
}
....

== Комментарии в языке CelestaSQL

CelestaSQL поддерживает стандартные однострочные и многострочные комментарии, а также комментарии <<CelestaDoc,CelestaDoc>>:

[source,sql]
-- однострочный комментарий
/*многострочный
    комментарий*/
 /**комментарий CelestaDoc*/


Обычные комментарии могут использоваться в любом месте текста, комментарии CelestaDoc — только непосредственно перед определением гранулы, таблицы, поля или индекса.

== Идентификаторы объектов в языке CelestaSQL

Идентификаторы объектов — это, иначе говоря, имена гранул, таблиц, полей, индексов, ограничений и представлений, их синтаксис в Celesta имеет ряд строгих ограничений.

. В обычных СУБД дозволяется, чтобы идентификаторы объектов содержали знаки пробела и неалфавитные знаки, если эти имена заключены в обрамляющие символы, например «[]» для MS SQL Server. Т. е. в MS SQLServer допустимо, например, такое имя таблицы: [Long Table$Name]. Celesta, однако, не может поддерживать пробелы и неалфавитные знаки в идентификаторах потому, что имя каждой Celesta-таблицы должно являться именем Java-класса, а имя каждого Celesta-поля — именем Java-переменной. Поэтому идентификатор любого именованного объекта CelestaSQL должен как минимум удовлетворять правилам наименования переменной в Java, т. е. *может состоять только из больших и малых букв латинского алфавита, цифр и знаков подчёркивания, при этом не может начинаться с цифры*.

. *Заключение идентификаторов Celesta в кавычки* в скриптах CelestaSQL *не допускается* на уровне синтаксиса, т. к. практической надобности в этом нет (имена никогда не содержат пробелов). На системном уровне при формировании запросов к СУБД Celesta, однако, всегда заключает имена своих объектов в прямые кавычки ("ANSI quotes"), чтобы гарантировать, что базы данных Oracle, PostgreSQL и H2 не будут нарушать регистр букв, составляющих идентификатор.

. *Идентификаторы* в Celesta *являются чувствительными к регистру*, однако нельзя создавать две таблицы, имена которых отличаются только регистром.

. *Длина* любого идентификатора в Celesta *не может быть больше 30 символов*.

. *Идентификаторы (префиксы) гранул, кроме того, не могут содержать в себе знаков подчёркивания*. Это связано с тем, что комбинация имени гранулы со знаком подчёркивания и другим идентификатором зачастую используется во внутрисистемных целях Celesta, и запрет на использование знака подчёркивания в именах гранул необходим для исключения возможных неоднозначностей.

[[create_schema_statement]]
== Конструкция CREATE SCHEMA (GRAIN)

С выражения CREATE SCHEMA должен начинаться любой скрипт определения гранулы. Используется следующий синтаксис (слова GRAIN и SCHEMA являются синонимами):

[[create_grain]]
[syntrax,create_schema,svg,heading="create_grain",opts=interactive]   
....
indentstack(3,
  line('CREATE', 
       choice('GRAIN', 'SCHEMA'), '/<grain_name>'),
  line('VERSION', '\'', '/<grain_version_tag>', '\''),
  line(opt('WITH', 'NO', 'AUTOUPDATE'))
)
....

Опция WIH NO AUTOUPDATE исключает схему целиком из процесса автообновления базы данных. Как и соответствующая <<celestasql_with_options,опция таблицы>>, может быть использована в ситуации, когда структура схемы находится под внешним управлением.

Указание версии обязательно для исключения непроизвольного автоматического даунгрейда базы данных при запуске старой версии гранулы на более свежей версии базы данных.

[[version_tags]]
Версия состоит из перечисленных через запятую компонент и может выглядеть таким образом: `1.23,TITAN3.34`. Читать это нужно следующим образом: базовая версия 1.23, доработка для проекта TITAN – 3.34. Регулярное выражение для проверки формата компонента: `([A-Z_]*)([0-9]+\\.[0-9]+)`. Требуется, чтобы каждая из составляющих версии имела двухкомпонентный (и только  двухкомпонентный!) формат, а префикс либо отсутствовал, либо состоял из заглавных латинских букв и знака подчёркивания. Когда  система определяет возможность автоапгрейда, сравниваются все тэги версии последовательно. 

В этом смысле, по отношению к тэгу «1.23,TITAN3.34»:

* «1.23,TITAN3.35» – более свежая версия (обновилась модификация), можно выполнять автоапгрейд
* «1.24,TITAN3.34» – более свежая версия (обновилась базовая версия), можно выполнять автоапгрейд
* «1.23,TITAN3.34,PLUTO1.00» – более свежая версия (добавилась ещё одна модификация), можно выполнять автоапгрейд
* «TITAN3.34,1.23» – та же самая версия (порядок следования тэгов не играет роли), автоапгрейд выполняться будет лишь при несовпадении контрольных сумм, ошибки не произойдёт
* «1.22,TITAN3.34» – более старая базовая версия, автоапгрейд выполняться не будет, произойдёт ошибка и Celesta остановится.
* «1.22,TITAN3.36» – несогласующаяся версия, апдейт выполняться не будет, ошибка. Версии «1.23,PLUTO1.00», «1.25» также будут несогласующимся с версией «1.23,TITAN3.34» и не станут накатываться автоматически (для самоконтроля попробуйте объяснить себе, почему).

Каждая из версий сравнивается, как число с плавающей запятой.

[[create_sequence_statement]]
== Конструкция CREATE SEQUENCE

Используется следующий синтаксис:

[[create_sequence]]
[syntrax,create_sequence,svg,heading="create_sequence",opts=interactive]   
....
indentstack(3,
  line('CREATE', 'SEQUENCE','/<sequence_name>'),
  line(loop(
     choice(line('START', 'WITH', '/<integer_literal>'),
            line('INCREMENT', 'BY', '/<integer_literal>'),
            line('MINVALUE', '/<integer_literal>'),
            line('MAXVALUE', '/<integer_literal>'),
            'CYCLE'),
     None
  ))
)
....

Основными ограничениями и отличиями такого запроса от SQL-запросов в различных СУБД являются:

. Не поддерживается в версиях MSSQL ниже 2011

. Если не указано значение MINVALUE, то оно автоматически выставляется равным значению START WITH (по умолчанию 1)

. Если не указано значение MAXVALUE, то оно автоматически выставляется равным значению Long.MAX_VALUE

. Значение START WITH не обновляется для созданных ранее последовательностей, даже если было изменено в файле гранулы (связано с тем, что oracle разрешает данную операцию только через удаление и пересоздание последовательности, а идеология celesta не предусматривает удаление statefull объектов из БД)

. Если в грануле присутствует таблица с именем, например, A, то является недопустимым создание последовательности с именем A_seq, так как это имя зарезервировано системой

[[create_table_statement]]
== Конструкция CREATE TABLE

Используется следующий синтаксис:

[[create_table]]
[syntrax,create_table,svg,heading="create_table",opts=interactive] 
....
indentstack(3,
  line('CREATE', 'TABLE','/<table_name>'),
  line('(', loop('/table_constituent', ','), ')', opt('/table_options')))

url_map = {
  'table_constituent': '.#table_constituent',
  'table_options': '.#table_options'
}
....

[[table_constituent]]
[syntrax,table_constituent,svg,heading="table_constituent",opts=interactive]
....
choice(
  '/field_definition',
  line(optx('CONSTRAINT', '/<pk name>'), '/primary_key_definition'),
  line(optx('CONSTRAINT', '/<fk name>'), '/foreign_key_definition')
)

url_map = {
  'field_definition': '.#field_definition',
  'primary_key_definition': '.#primary_key_definition',
  'foreign_key_definition': '.#foreign_key_definition'
}
....

Иными словами, в конструкции CREATE TABLE в скобках через запятую в любом порядке могут быть перечислены определения полей, определения первичных ключей или определения внешних ключей, а за скобками, возможно, перечислены опции. На практике определения всех полей идут подряд в самом начале, далее — определения составных первичных ключей (первичные ключи, состоящие из одного поля, можно определять на самом поле) и определения составных внешний ключей (опять же, внешние ключи, состоящие из одного поля, можно определять на самом поле).

=== Определения полей
[[field_definition]]
[syntrax,field_definition,svg,heading="field_definition",opts=interactive]
....
indentstack(6, 
 line(
    '/<field name>',
    choice(
        '/int_field',
        '/floating_field',
        '/decimal_field',
        '/text_field',
        '/blob_field',
        '/datetime_field',
        '/datetime_with_time_zone_field',
        '/bit_field')),
 line(
    opt('PRIMARY', 'KEY'),
    opt('/inline_fk_definition')
 )
)

url_map = {
  'int_field': '.#int_field',
  'floating_field': '.#floating_field',
  'decimal_field': '.#decimal_field',
  'text_field': '.#text_field',
  'blob_field': '.#blob_field',
  'datetime_field': '.#datetime_field',
  'datetime_with_time_zone_field': '.#datetime_with_time_zone_field',
  'bit_field': '.#bit_field',
  'inline_fk_definition': '.#inline_fk_definition'
}
....

*field_definition* (Определение поля) — конструкция, задающая тип поля, название поля, его свойства NULL/NOT NULL и DEFAULT, опционально может заканчиваться конструкцией PRIMARY KEY и/или FOREIGN KEY.

Сокращенное определение внешнего ключа (*inline_fk_definition*) имеет следующий синтаксис:

[[inline_fk_definition]]
[syntrax,inline_fk_definition,svg,heading="inline_fk_definition"]
....
rightstack(
line(
  'FOREIGN',
  'KEY',
  'REFERENCES',
  '/table_ref'),
line(
  '(',
  '/<field name>',
  ')',
  '/fk_rules')
)

url_map = {
  'table_ref': '.#table_ref',
  'fk_rules': '.#fk_rules'
}
....

Здесь *table_ref* — ссылка на таблицу, которая может быть однокомпонентной (если таблица, на которую указывает внешний ключ, находится в текущей грануле) или двухкомпонентной, с явным указанием имени гранулы:

[[table_ref]]
[syntrax,table_ref,svg,heading="table_ref",opts=interactive]
....
line(optx('/<grain name>', '.'), '/<table name>')
....

Определение синтаксиса правил внешних ключей (*fk_rules*) см. в разделе <<foreign_keys_statements,Внешние ключи»>>.

[[datatypes_mapping]]
=== Типы данных

Используется следующая система типов данных.

[cols="1, 1, 1, 1, 1, 1, 1, 1, options="header"]
|====
^.^|
^.^|CELESTA
^.^|Microsoft SQL Server
^.^|Oracle
^.^|PostgreSQL
^.^|Firebird
^.^|H2
^.^|Java Type For Cursor

|Integer (32-bit)
|INT
|INT
|NUMBER
|INT4
|INTEGER
|INTEGER
|java.lang.Integer

|Floating point (64-bit)
|REAL
|FLOAT(53)
|REAL
|FLOAT8
[= DOUBLE PRECISION]
|DOUBLE PRECISION
|DOUBLE
|ava.lang.Double

|Fixed point (decimal)
|DECIMAL(p,s)
|DECIMAL(p,s)
|NUMBER(p,s)
|NUMERIC(p,s)
|DECIMAL(p,s)
|DECIMAL(p,s)
|java.math.BigDecimal

|String (Unicode)
|VARCHAR(n)
|NVARCHAR(n)
|NVARCHAR(n)
|VARCHAR(n)
|VARCHAR(n)
|VARCHAR(n)
|java.lang.String

|Long string (Unicode)
|TEXT
|NVARCHAR(MAX)
|NCLOB
|TEXT
|BLOB SUB_TYPE TEXT
|CLOB
|java.lang.String

|Binary
|BLOB
|VARBINARY(MAX)
|BLOB
|BYTEA
|BLOB
|VARBINARY(MAX)
|java.lang.String

|Date/Time
|DATETIME
|DATETIME
|TIMESTAMP
|TIMESTAMP
|TIMESTAMP
|TIMESTAMP
|java.util.Date

|DateTime With Time Zone
|DATETIME WITH TIME ZONE
|DATETIMEOFFSET
|TIMESTAMP WITH TIME ZONE
|TIMESTAMPZ
|TIMESTAMP WITH TIME ZONE
|TIMESTAMP WITH TIME ZONE
|java.time.ZonedDateTime

|Boolean
|BIT
|BIT
|NUMBER
[check in (0, 1)]
|BOOL
|SMALLINT
[check in (0, 1)]
|BOOLEAN
|java.lang.Boolean

|====


См. также раздел «<<RDBMS_peculiarities,Особенности работы Celesta с поддерживаемыми типами СУБД>>».

Для каждого типа поля имеется свой вариант определения:

[[nullability]]
[syntrax,nullability,svg,heading="nullability",opts=interactive]
....
optx(optx('NOT'), 'NULL')
....

[[int_field]]
[syntrax,int_field,svg,heading="int_field",opts=interactive]
....
line('INT', '/nullability', 
optx('DEFAULT', choice('/<integer literal>', 
                     line('NEXTVAL', '(', '/<sequence name>', ')'))))
url_map = {
  'nullability': '.#nullability'
}
....

Вместо конструкции DEFAULT <целое число> для поля с типом INT может использоваться конструкция NEXTVAL(<sequence name>). Таким образом значение колонки будет инкрементироваться при вставке в зависимости от указанной последовательности. Стоит отметить, что можно использовать только последовательности, объявленные в той же грануле, что и таблица, к которой принадлежит колонка.

[[floating_field]]
[syntrax,floating_field,svg,heading="floating_field",opts=interactive]
....
line('REAL', '/nullability', 
optx('DEFAULT', '/<float.-point literal>'))

url_map = {
  'nullability': '.#nullability'
}
....

[[decimal_field]]
[syntrax,decimal_field,svg,heading="decimal_field",opts=interactive]
....
indentstack(3,
line('DECIMAL', '(', '/<integer literal>', ',' , '/<integer literal>', ')'),
line('/nullability', optx('DEFAULT', '/<float.-point literal>'))
)

url_map = {
  'nullability': '.#nullability'
}
....

[[text_field]]
[syntrax,text_field,svg,heading="text_field",opts=interactive]
....
indentstack(10,
line(choice(line('VARCHAR', '(', '/<integer literal>', ')'),
            'TEXT')),
line('/nullability', optx('DEFAULT', '/<text literal>'))
)

url_map = {
  'nullability': '.#nullability'
}
....

[[blob_field]]
[syntrax,blob_field,svg,heading="blob_field",opts=interactive]
....
line('BLOB', '/nullability', 
optx('DEFAULT', '/<binary literal>'))

url_map = {
  'nullability': '.#nullability'
}
....

Здесь *<binary literal>* — шестнадцатеричное представление последовательности байтов, начинающееся с 0x и не заключённые в кавычки, например: 0xFFAAFFAAFF.

[[datetime_field]]
[syntrax,datetime_field,svg,heading="datetime_field",opts=interactive]
....
line('DATETIME', '/nullability', 
optx('DEFAULT', choice(line('\'', '/<YYYYMMDD>', '\''),
                       'GETDATE()')))

url_map = {
  'nullability': '.#nullability'
}
....

В качестве значения DEFAULT для поля с типом DATETIME может использоваться функция GETDATE() (текущий момент времени).

[[datetime_with_time_zone_field]]
[syntrax,datetime_with_time_zone_field,svg,heading="datetime_with_time_zone_field",opts=interactive]
....
line('DATETIME', 'WITH', 'TIME', 'ZONE', '/nullability')

url_map = {
  'nullability': '.#nullability'
}
....

[[bit_field]]
[syntrax,bit_field,svg,heading="bit_field",opts=interactive]
....
line('BIT', '/nullability', optx('DEFAULT', choice('TRUE', 'FALSE')))

url_map = {
  'nullability': '.#nullability'
}
....

=== Первичные ключи

[[primary_key_definition]]
[syntrax,primary_key_definition,svg,heading="primary_key_definition",opts=interactive]
....
line('PRIMARY', 'KEY', '(', loop('/<field name>', ','), ')')
....

*primary_key_definition* (определение первичного ключа) — конструкция, задающая состав полей, входящих в первичный ключ таблицы. Возможно в двух вариантах:

* сокращённый вариант — когда ключевые слова “PRIMARY KEY” идут сразу после определения поля, это даёт возможность более короткой и наглядной записи в случае, когда первичный ключ состоит всего из одного поля

* полный вариант — когда конструкция PRIMARY KEY находится в определении таблицы среди определения полей, и может содержать как одно поле, так и любое количество полей.

Ограничения:

* *Самое важное: для обеспечения работоспособности системы не допускается создание таблиц без PRIMARY KEY*. (За исключением READ ONLY-таблиц).

* В таблице может быть не более одного упоминания PRIMARY KEY, будь то сокращённое выражение в конце определения поля или составное выражение в определении таблицы.

* Не допускается создание PK по полям с типами BLOB и TEXT.

* Не допускается создание PK по nullable-полям.

* Не допускается более одного вхождения одного и того же поля в определение PRIMARY KEY.

[[foreign_keys_statements]]
=== Внешние ключи

[[foreign_key_definition]]
[syntrax,foreign_key_definition,svg,heading="foreign_key_definition",opts=interactive]
....
indentstack(3,
line(
  'FOREIGN',
  'KEY',
  '(',
  loop('/<field name>', ','),
  ')'),
line(
  'REFERENCES',
  '/table_ref',
  '(',
  loop('/<field name>', ','),
  ')',
  '/fk_rules'
))

url_map = {
  'table_ref': '.#table_ref',
  'fk_rules': '.#fk_rules'
}
....

*foreign_key_definition* (Определение внешнего ключа) — конструкция, задающая связь между таблицами по одному или нескольким полям. Как и в случае с конструкцией PRIMARY KEY, возможно использование в двух вариантах — сокращённом (встроенном в определение поля, связь по одному полю) и полном (перечисляется среди определений полей). Кроме того, внешний ключ можно создать вне определения таблицы при помощи конструкции "alter table add constraint foreign key":

[[add_foreign_key]]
[syntrax,add_foreign_key,svg,heading="add_foreign_key",opts=interactive]
....
indentstack(3,
line(
  'ALTER',
  'TABLE',
  '/<table name>'),
line(
  'ADD',
  'CONSTRAINT',
  '/<fk name>',
  '/foreign_key_definition'
))

url_map = {
  'foreign_key_definition': '.#foreign_key_definition'
}
....

Ограничения:

* Foreign key, простой или составной, может ссылаться только на Primary Key, причём полностью. (В Celesta SQL не допускаются ограничения UNIQUE, поэтому из двух возможностей, стандартно предлагаемых в СУБД для Foreign Keys, остаётся только возможность ссылки на Primary Key).

* Типы полей должны в точности совпадать (если поле – строковое, длина ссылающегося поля должна быть точно равна длине поля, на которое ссылаются).

* Нельзя создать более одного определения Foreign Key на одном и том же наборе столбцов (частный случай – не может быть двух FK, определённых для одного и того же столбца).

*fk_rules* — ссылочные действия:

[[fk_rules]]
[syntrax,fk_rules,svg,heading="fk_rules",opts=interactive]
....
indentstack(6,
  line(optx(line('ON', 'UPDATE',
    choice(line('NO', 'ACTION'), 'CASCADE', line('SET', 'NULL'))))),
  line(optx(line('ON', 'DELETE',
    choice(line('NO', 'ACTION'), 'CASCADE', line('SET', 'NULL')))))
)
....

Поддерживаемые ссылочные действия:

* `NO ACTION` – запрет удаления/модификации родительской записи, если на неё есть ссылки

* `SET NULL` – выставление `NULL` в ссылках. Внимание: естественно, использовать это действие запрещено для `NOT NULL`-able полей

* `CASCADE` – каскадное удаление/обновление полей.

В момент создания foreign key сослаться можно только

* на таблицу, определённую в текущей грануле выше по тексту

* на таблицу, определённую с другой грануле.

WARNING:  «Зацикленные» ссылки по foreign key (например, вида A->B->C->A) при разработке структуры базы данных в действительности нужны крайне редко и обычно говорят об ошибке проектировщика. Единственный широко применимый практически значимый пример «зацикливания» — ссылка таблицы на саму себя при организации иерархического перечня по принципу parent-child.

В Celesta не допускается создание «зацикленных» ссылок между таблицами, принадлежащими разным гранулам. Если надо организовать ссылки по кругу между несколькими таблицами внутри гранулы, то это можно сделать, воспользовавшись конструкцией "alter table add constraint foreign key".

В частности, работает следующий пример:

[source, sql]
CREATE TABLE aa(idaa INT NOT NULL PRIMARY KEY, idc INT , textvalue nvarchar(10));

[source, sql]
CREATE TABLE a (ida INT NOT NULL PRIMARY KEY, descr nvarchar(2), parent INT
                FOREIGN KEY REFERENCES a(ida), --ссылка таблицы на саму себя
                fff INT FOREIGN KEY REFERENCES aa(idaa) --первая часть круговой ссылки

внешний ключ, создаваемый вне таблицы:

```sql
ALTER TABLE aa ADD CONSTRAINT fk1
  FOREIGN KEY (idc) REFERENCES a(ida); --вторая часть круговой ссылки
```

Пример создания составного ключа, состоящего из двух полей:

```sql
CREATE TABLE empfiles(
  id INT NOT NULL PRIMARY KEY,
  user_id varchar(200) NOT NULL,
  orgtype_id varchar(255) NOT NULL,
  question_id varchar(30) NOT NULL,
  FOREIGN KEY (orgtype_id, question_id) REFERENCES schema.table(field, field)
```

[[celestasql_with_options]]
=== Опции

Celesta позволяет указывать следующие опции после определения таблицы:

[[table_options]]
[syntrax,table_options,svg,heading="table_options",opts=interactive]
....
rightstack(
  line('WITH',
    choice(
      line('READ', 'ONLY'),
      line(optx('NO'), 'VERSION', 'CHECK')
    )),
  line(opt(line('NO', 'AUTOUPDATE')))
)
....

Таким образом, поддерживаются следующие возможности:

* `WITH VERSION CHECK` — режим по умолчанию: включение механизма отслеживания версий записей для исключения потерянных обновлений (см. раздел Защита от потерянных обновлений). Указывать данную опцию явно не требуется.

* `WITH NO VERSION CHECK` — отключение механизма отслеживания версий записей. Требуется в случаях, когда нет желания вводить новое системное поле в таблицу. Возможность модифицировать данные в таблице при этом сохраняется, но возможны «потерянные обновления».

* `WITH READ ONLY` — режим «только чтение». Требуется в случаях, когда данные таблицы поступают из внешних источников, а не заносятся средствами Celesta, либо если необходимо подключиться к таблице, относящейся к иному приложению, и потому нежелательно вносить в её структуру какие-либо изменения. В этом режиме механизм отслеживания версий записей отключается, а ORM-класс для доступа к таблице генерируется без методов модификации данных. Кроме того, для таких таблиц не требуется указывать первичный ключ.

* Опция `NO AUTOUPDATE`, которая может применяться совместно с данными опциями, отключает таблицу от процесса автообновления базы данных. Используется в случае, когда структура какой-либо таблицы изменяется в базе данных вручную и система не должна пытаться синхронизировать структуру этой таблицы с описанием на языке CelestaSQL автоматически.

[[create_index_statement]]
== Конструкция CREATE INDEX

Индексы применяются для ускорения фильтрации по полям таблиц и создаются при помощи следующей синтаксической конструкции:

[[create_index]]
[syntrax,create_index,svg,heading="create_index",opts=interactive]
....
rightstack(
line(
  'CREATE',
  'INDEX',
  '/<index name>',
  'ON',
  '/<table name>'),
line(
  '(',
  loop('/<field name>', ','),
  ')'
)
)
....

Имена индексов должны быть уникальны в пределах гранулы. Все индексы в Celesta допускают неуникальные значения.

[[create_view_statement]]
== Конструкция CREATE VIEW

Представления (views) служат для доступа только на чтение к данным, собранным из одной или нескольких таблиц при помощи SQL-запроса SELECT. Для каждого своего представления Celesta создаёт объект-представление в базе данных, транслируя при этом SQL-запрос на языке CelestaSQL в соответствующий диалект языка SQL.

Представления создаются при помощи синтаксической конструкции

[[create_view]]
[syntrax,create_view,svg,heading="create_view",opts=interactive]
....
line(
  'CREATE',
  'VIEW',
  '/<view name>',
  'AS',
  '/query')

url_map = {
  'query': '.#query'
}
....

* *<view name>* (имя представления) должно быть уникальным в пределах гранулы и не совпадать с именем таблицы.

* *query* (запрос) представляет собой SQL-запрос, имеющий следующий синтаксис:

[[query]]
[syntrax,query,svg,heading="query",opts=interactive]
....
rightstack(
  line(
   'SELECT',
    opt('DISTINCT'),
    loop(
        choice(
            line('/term',
                 opt('AS', '/<field alias>')),
            line('/aggregate')
        ),
        ',')
   ),
   line(
    'FROM',
    '/from_clause',
    optx('WHERE', '/condition'),
    optx('/group_by')
   )
)

url_map = {
  'term': '.#term',
  'aggregate': '.#aggregate',
  'from_clause': '.#from_clause',
  'condition': '.#condition',
  'group_by': '.#group_by'
}
....

[[from_clause]]
[syntrax,from_clause,svg,heading="from_clause",opts=interactive]
....
indentstack(3,
  line('/table_ref', optx('AS', '/<table alias>')),
  line(optx(
        loop(indentstack(10,
            line(choice('INNER', 'LEFT', 'RIGHT'),
                  'JOIN',
                  '/table_ref',
                  optx('AS', '/<table alias>')),
            line(
                  'ON',
                  '/condition')),
             None
             )
    )
  )
)

url_map = {
  'table_ref': '.#table_ref',
  'condition': '.#condition'
}
....

Основными ограничениями и отличиями такого запроса от SQL-запросов в различных СУБД являются:

. Запросы строятся только на таблицах (текущей гранулы или соседних гранул). Во избежание выстраивания неэффективных конструкций невозможно построение запросов на представлениях.

. Конструкция SELECT * не поддерживается, и всякое поле запроса, если только это не ссылка на поле таблицы с уникальным в рамках запроса именем, должно иметь определённый и уникальный псевдоним. Это нужно для возможности однозначного создания класса-курсора, поля которого соответствуют именам столбцов запроса.

. Не поддерживается конструкция ORDER BY, т. к. при необходимости определённым образом отсортировать результирующий набор следует воспользоваться методом orderBy(...) соответствующего курсора.

. Не поддерживается конструкция GROUP BY...HAVING (разработка поддержки этой конструкции возможна лишь при возникновении обоснованной необходимости в данной функциональности).

. Не поддерживаются FULL JOIN (объединения LEFT и RIGHT joins) и CROSS JOIN (декартовы произведения таблиц). Практическая значимость FULL JOIN сомнительна. CROSS JOIN сам по себе также не бывает практически необходим, неосторожное использование может привести к проблемам производительности.

. Не поддерживаются конструкции UNION, WITH, любые вложенные запросы. Конструкция бизнес-приложения должна предусматривать достаточное количество таблиц с данными, чтобы в этих конструкциях не было необходимости.

Ссылка на таблицу (*table_ref*) имеет синтаксис

[syntrax,table_ref,svg,heading="table_ref",opts=interactive]
....
line(optx('/<grain name>', '.'), '/<table name>')
....

Имя гранулы указывать не обязательно, если таблица находится в той же грануле, что и текущее представление.

Терм, определяющий поле представления, имеет следующий синтаксис:

[[term]]
[syntrax,term,svg,heading="term",opts=interactive]
....
loop(
  line(opt('-'),
    choice(
      '/primary_term',
      line('(', '/term', ')'))),
  choice('+', '-', '*', '/', '||')
)

url_map = {
  'primary_term': '.#primary_term',
  'term': '.#term'
}
....

Над выражениям типа `INT` и `REAL` допустимы обычные арифметические операции с обычным приоритетом: максимальный приоритет у унарного минуса, далее — умножение и деление («*», «/»), далее — сложение и вычитание («+», «-»). Над выражениями типа `VARCHAR` допустима операция конкатенации «||». Операции над полями прочих типов недопустимы.

[[primary_term]]
[syntrax,primary_term,svg,heading="primary_term",opts=interactive]
....
choice(
  line(optx(line(choice('/<table name>', '/<table alias>'), '.')),
       '/<field name>'),
  '/<string literal>',
  '/<integer literal>',
  '/<float.-point literal>',
  'TRUE',
  'FALSE',
  'GETDATE()',
  '/<$param id>'
)
....

Ссылки на поля могут быть однокомпонентными (если они однозначно указывают на поле определённой таблицы) либо двухкомпонентными, в этом случае в качестве первой компоненты следует указывать псевдоним таблицы из конструкции `FROM` либо — если явный псевдоним отсутствует — имя таблицы.

Специальный вид идентификатора *<$param id>* -- знак $, за которым следует идентификатор -- служит для ссылок на параметры <<create_function_statement,функций>>.

Наконец, синтаксис логического выражения *condition*, используемого в конструкциях `JOIN` ... `ON` и `WHERE`:

[[condition]]
[syntrax,condition,svg,heading="condition",opts=interactive]
....
loop(
  line(optx('NOT'),
       choice('/predicate',
          line('(', '/condition', ')'))),
  choice('AND', 'OR')
)

url_map = {
  'predicate': '.#predicate',
  'condition': '.#condition'
}
....

[[predicate]]
[syntrax,predicate,svg,heading="predicate",opts=interactive]
....
line(
'/term',
choice(
      line(choice('=', '>', '>=', '<=', '<', '<>', 'LIKE'),
           '/term'),
      line('BETWEEN', '/term', 'AND', '/term'),
      line('IN', '(', loop('/term', ','), ')'),
      line('IS', 'NULL')
))

url_map = {
  'term': '.#term'
}
....

[[aggregate]]
[syntrax,aggregate,svg,heading="aggregate",opts=interactive]
....
line(
  choice(
    line('COUNT', '(', '*', ')'),
    line(
        choice(
            'SUM',
            'MIN',
            'MAX'
        ),
        line('(', '/term', ')')
    )
  ),
  'AS', '/<field alias>')
  
url_map = {
  'term': '.#term'
}
....

Следует отметить, что *term* внутри конструкции `SUM` должен являться числом.

[[group_by]]
[syntrax,group_by,svg,heading="group_by",opts=interactive]
....
line (
  'GROUP', 'BY',
  loop(
      choice(
          '/<field name>',
          '/<field alias>'
      ),
      ','
  )
)
....

Особенность конструкции GROUP BY в Celesta-SQL заключается в необходимости всегда перечислять в ней все неагрегатные колонки из выборки.


[[create_materialized_view_statement]]
== Конструкция CREATE MATERIALIZED VIEW

Материализованные представления (materialized views) служат для доступа только на чтение к агрегатным данным, собранным из одной таблицы и объединенным при помощи выражения GROUP BY. Для каждого своего материализованного представления Celesta создаёт таблицу в базе данных, модифицируемую триггерами при изменении родительской таблицы.

Материализованные представления создаются при помощи синтаксической конструкции

[[create_materialized_view]]
[syntrax,create_materialized_view,svg,heading="create_materialized_view",opts=interactive]
....
rightstack( 
line(
  'CREATE',
  'MATERIALIZED',
  'VIEW',
  '/<view name>',
  'AS'),
line(
  'SELECT',
  loop(
      choice(
          line('/materialized_aggregate'),
          line('/<field name>', 
              optx('AS', '/<field alias>')
          )
      ),
      ','
  )),
line(
  'FROM',
  '/table_ref',
  '/group_by'
))

url_map = {
  'materialized_aggregate': '.#materialized_aggregate',
  'table_ref': '.#table_ref',
  'group_by': '.#group_by'
}
....

Основными ограничениями и отличиями такого запроса от SQL-запросов в различных СУБД являются:

. Запросы строятся только на таблице текущей гранулы.

. Конструкция SELECT * не поддерживается, и всякое поле запроса, если только это не ссылка на поле таблицы с уникальным в рамках запроса именем, должно иметь определённый и уникальный псевдоним. Это нужно для возможности однозначного создания класса-курсора, поля которого соответствуют именам столбцов запроса.

. В выборке обязательно должен участвовать хотя бы один агрегатный и хотя бы один неагрегатный столбец.

. Неагрегатные колонки должны ссылаться на not null колонки родительской таблицы.

. Если в group by выражении участвует колонка типа datetime, то ее значения будут округляться в точности до дня (часы, минуты и более точные измерения отсекаются).

. Из агрегирующих операций доступны только `SUM` и `COUNT`.

[[materialized_aggregate]]
[syntrax,materialized_aggregate,svg,heading="materialized_aggregate",opts=interactive]
....
line(
  choice(
    line('COUNT', '(', '*', ')'),
    line(
      'SUM', '(', '/term', ')'
    )
  ),
  'AS', '/<field alias>')

url_map = {
  'term': '.#term'
}
....

[[create_function_statement]]
== Конструкция CREATE FUNCTION

Функции — они же параметризованные представления. Служат для доступа только на чтение к данным, собранным из одной или нескольких таблиц при помощи SQL-запроса SELECT с учетом переданных параметров.

Функции создаются при помощи синтаксической конструкции

[[create_function]]
[syntrax,create_function,svg,heading="create_function",opts=interactive]
....
indentstack(3,
 line(
  'CREATE',
  'FUNCTION',
  '/<function name>'
 ), 
 line(
 '(',
  loop(
     '/param_definition',
     ','
  ),
  ')',
  'AS',
  '/query'
 )
)

url_map = {
  'param_definition': '.#param_definition',
  'query': '.#query'
}
....


Параметры декларируются через запятую, с заданием имени и типа параметра:

[[param_definition]]
[syntrax,param_definition,svg,heading="param_definition",opts=interactive]
....
line(
'/<param name>',
choice(
  'INT',
  'REAL',
  'DECIMAL',
  'VARCHAR',
  'DATETIME',
  'BIT'
))
....

Чтобы сослаться на параметр в выражении функции, необходимо перед именем параметра ставить знак `$` (например, `param1` будет фигурировать в выражении запроса как `$param1`).

Основными ограничениями и отличиями такого запроса от SQL-запросов в различных СУБД являются:

. Конструкция SELECT * не поддерживается, и всякое поле запроса, если только это не ссылка на поле таблицы с уникальным в рамках запроса именем, должно иметь определённый и уникальный псевдоним. Это нужно для возможности однозначного создания класса-курсора, поля которого соответствуют именам столбцов запроса.

. В объявлении обязательно должен иметься хотя бы один параметр.

. Все объявленные параметры обязательно должны использоваться.

В остальном синтаксическое выражение аналогично обычному View.

Пример функции:

[source, sql]
CREATE FUNCTION pView2(param int,/*TEST*/ param2 varchar) AS
  select f1, f2, f3 from t1
  where f2 = $param AND f3 = $param2 AND f3 = $param2;

//end::celesta_sql[]
