= Контекст вызова
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs

//tag::call_context[]

Для того, чтобы можно было реализовать требования распределения прав доступа и логирования действий, любая операция над данными в Celesta производится от имени некоторого пользователя, «анонимных» операций быть не может. Поэтому любой Celesta-код выполняется в некотором контексте вызова (CallContext).

Привязка имени пользователя к роли определяет разрешения на доступ к таблицам, а также обеспечивает возможность логирования изменений, производимых от его имени.

Каждая из процедур, вызываемых в Celesta, принимает в качестве аргумента объект `ru.curs.celesta.CallContext`. Этот объект предназначен в первую очередь для использования в качестве аргумента при вызове конструкторов курсоров. Cам этот объект имеет следующие публично доступные методы и атрибуты:

commit():: фиксирует текущую транзакцию. Вызывать данный метод требуется только в редких случаях, когда транзакцию обработки данных необходимо разбить на несколько частей. Обычно в вызове этого метода необходимости нет, т. к. транзакция фиксируется автоматически по завершении процедуры.

rollback():: откатывает текущую транзакцию.

getCelesta():: вызывает текущий экзмемпляр объекта Celesta. Необходимо, например, для получения информации о метаданных.

getUserId():: возвращает имя пользователя, от лица которого производятся действия.

getStartTime():: возвращает время создания контекста вызова (время начала работы Celesta-процедуры).

getDurationNs():: возвращает время жизни контекста вызова в наносекундах (необходимо использовать данный метод для точного замера времени выполнения процедур).

getProcName():: возвращает имя процедуры, которая была изначально вызвана (используется для нужд отладки).

getDBPid():: возвращает PID (process identifier) текущего соединения с базой данных (используется для нужд отладки).


//end::call_context[]
