= BLOB-поля
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs

//tag::blob[]


BLOB-поля позволяют хранить в ячейке таблицы большие объёмы данных — например, целые файлы с документами. Работа с этими полями через курсор отличается от работы с полями других типов.

. Атрибуты курсора, соответствующие BLOB-полям, должны принимать значения со специальным типом BLOB, и никак иначе. Присвоение этим атрибутам строк и значений иных типов приведёт к ошибке при попытке вызова методов insert() или update().

. Получить экземпляр класса BLOB и присвоить его атрибуту курсора можно только одним способом: вызвав в курсоре метод calc<имяполя>(). Например, если BLOB-поле имеет название foo, то соответствующий метод курсора называется calcfoo(), и после его вызова будет заполнен атрибут foo.

. В отличие от полей других типов, которые автоматически заполняются данными таблицы при чтении записи методами get(), next() и т. п., BLOB-поля при выполнении этих методов не заполняются, а всегда получают значение None. Чтобы прочитать BLOB-поле, необходимо вызвать метод calc...(). При этом, если курсор указывает на существующую в таблице запись, вызов метода calc...() приведёт к чтению содержимого BLOB-а из базы данных в оперативную память. Поэтому calc...() следует вызывать лишь тогда, когда есть намерение прочитать или изменить содержимое BLOB-а.

. После вызова метода calc<имяполя>(), соответствующий атрибут курсора инициализируется объектом с типом BLOB. Методы этого объекта позволяют читать и изменять его содержимое и описаны далее. После изменения содержимого объекта BLOB можно воспользоваться методом update() или insert().

. Если BLOB необходимо стереть из базы данных, записав в соответствующую ячейку значение NULL, нужно воспользоваться методом setNull() объекта BLOB, а затем вызвать update(). Присвоение атрибуту значения None, в отличие от полей других типов, не сработает, т. к. будет проинтерпретировано системой, как если бы BLOB не был прочитан из базы, и по update() ничего не изменится.

Методы класса BLOB:

getInStream():: возвращает экземпляр класса java.io.InputStream, из которого можно прочитать содержимое курсора или None, если в ячейке таблицы базы данных содержится значение NULL. Допускается многократный вызов этого метода, при этом всякий раз будет создаваться новый поток, читающий с начала.

getOutStream():: стирает все данные BLOB-а в памяти (если они были) и создаёт экземпляр java.io.OutputStream, в который можно записать данные для BLOB-а. Следует подчеркнуть, что каждый вызов getOutStream() удаляет из BLOB-а в памяти все данные, даже если в полученный поток ничего не будет записано. Также следует подчеркнуть, что этот метод меняет данные только в представлении BLOB в оперативной памяти, реальная запись в базу данных происходит только после вызова методов insert() или update() на курсоре.

setNull():: устанавливает для BLOB-а значение NULL.

isModified():: возвращает true, если первоначальные данные объекта были изменены вызовами getOutStream() или setNull().

size():: возвращает размер внутренних данных BLOB-а в байтах.

Примеры кода для работы с BLOB-полем:

[source, python]
import java.io.OutputStreamWriter as OutputStreamWriter
import java.io.InputStreamReader as InputStreamReader
import java.io.BufferedReader as BufferedReader
c = cCursor(context)
#Далее подразумевается, что c.dat — BLOB-поле
. . .
#Пример записи
c.init()
c.calcdat()
osw = OutputStreamWriter(c.dat.getOutStream(), 'utf-8')
try:
    osw.append('hello, blob field!')
finally:
    osw.close()
c.insert()
. . .
#Пример чтения
c.calcdat()
ins = c.dat.getInStream()
if ins: #Помним о том, что в поле может быть NULL
    inr = BufferedReader(InputStreamReader(ins, 'utf-8'))
    print inr.readLine() #в консоль будет выведено содержимое курсора,
                     #например, "hello, blob field!

//end::blob[]
