= Метаданные Celesta
:lang: ru
:is-main-doc:
include::_doc_general_attributes.adoc[]
:toclevels: 3
:doctype: book
:img: images
:lupa: icon:search[]
:source-highlighter: highlightjs

//tag::meta[]

== Метаданные и их динамическое изменение

Экземпляр класса {apidocs}ru/curs/celesta/Celesta.html[`Celesta`] доступен через метод *getCelesta()* переменной `{apidocs}ru/curs/celesta/CallContext.html[CallContext] context`, передаваемой в качестве аргумента в каждую процедуру обработки данных.

Через метод *getScore()* экземпляра класса Celesta разработчик решения может получить доступ к метаданным системы, построенным при разборе «партитуры» (парсинге SQL-файлов). Доступ к метаданным необходим для двух целей:

. получения информации о текущей структуре базы данных во время выполнения кода бизнес-логики,

. динамического изменения структуры базы данных.

Для динамического изменения структуры базы данных необходимо действовать в три этапа:

. Используя описанные далее методы объектов метаданных, изменить объектную модель данных в памяти (ограничение: попытка изменения объектов системной гранулы "celesta" приведёт к ошибке).

. Вызвать метод save() объекта Score. При этом система сериализует текущее состояние метаданных гранул в .sql-файлы партитуры Celesta, перезаписывая их текущее содержимое. *Перезаписываться будут лишь файлы тех гранул, которые были изменены*.

. Создать новый экземпляр класса Celesta. При этом произойдёт инициализация объекта Celesta на основе новой структуры базы данных и автоматическая миграция базы данных.

Следует понимать, что хотя Celesta не будет перезаписывать .sql-файл, если в этом нет нужды (если метаданные не были изменены), при перезаписи содержимого .sql-файлов происходит необратимая потеря комментариев и форматирования, существовавших в них ранее. Сохранены в тексте будут только CelestaDoc-комментарии. Поэтому динамическим изменением следует пользоваться с осторожностью.

== Состав метаданных

Все метаданные ({apidocs}ru/curs/celesta/score/Score.html[`Score`]) делятся на гранулы ({apidocs}ru/curs/celesta/score/Grain.html[`Grain`]), состоящие из таблиц ({apidocs}ru/curs/celesta/score/Table.html[`Table`]), индексов ({apidocs}ru/curs/celesta/score/Index.html[`Index`]) и представлений ({apidocs}ru/curs/celesta/score/View.html[`View`]).

* Таблицы состоят из столбцов ({apidocs}ru/curs/celesta/score/Column.html[`Column`]) и содержат внешние ключи.

* Индексы относятся к таблицам и состоят из их столбцов (Column).

* Представления состоят из столбцов представлений ({apidocs}ru/curs/celesta/score/ViewColumnMeta.html[`ViewColumnMeta`]), которые отличаются от столбцов таблиц, но имеют ряд общих свойств.

Ниже представлена диаграмма классов, описывающих метаданные.

[plantuml, metaclasses, png]
----
@startuml
abstract class GrainElement {
 +getGrain(): Grain
}

abstract class AbstractView {

}

abstract class NamedElement {
 +getName(): String
 +getQuotedName(): String
 +getCelestaDoc(): String
}

class Index {
}

class View {
}

class Table{
}

abstract class Column {

}

class Grain {
 +getScore()
 +getTables()
 +getIndices()
 +getViews()
}

class MaterializedView {

}

interface ViewColumnMeta {

}

GrainElement <|-- Index 
GrainElement <|-- AbstractView
AbstractView <|-- View
AbstractView <|-- MaterializedView
GrainElement <|-- Table
GrainElement <|-- SequenceElement

NamedElement <|-- GrainElement
NamedElement <|-- Column
NamedElement <|-- Grain

View <|-- ParameterizedView

class Score {
 +getGrains()
}

Score "1" -- "*" Grain

Grain "1" -- "*" Index

Grain "1" -- "*" View

Grain "1" -- "*" MaterializedView

Grain "1" -- "*" SequenceElement

Grain "1" -- "*" Table

Table "1" -- "1..*" Column

MaterializedView  "1" -- "1..*" Column

Table "1" -- "1..*" ForeignKey

ForeignKey "1" -- "1..*" Column

Index "1" -- "1..*" Column

View "1" -- "1..*" ViewColumnMeta

@enduml
----

Базовым интерфейсом для столбцов таблиц и представлений является интерфейс ColumnMeta, с помощью которого можно узнать Celesta-тип данных столбца, его nullability и CelestaDoc, привязанный к данному столбцу. Данный интерфейс реализуют классы ViewColumnMeta для описания полей представлений и Column для описания полей таблиц.

Класс Column является абстрактным, и для шести типов полей, поддерживаемых Celesta, от него наследуются шесть субклассов:

[plantuml, columnclasses, png]
----
@startuml
interface ColumnMeta{
 +jdbcGetterName(): String
 +getCelestaType(): String
 +getJavaClass(): Class
 +isNullable(): boolean
 +getCelestaDoc(): String
}

interface ViewColumnMeta {
 +getColumnType(): ViewColumnType
 +getLength(): int
}

abstract class Column {
 +getParentTable: TableElement
 +getDefaultValue: Object
 +getCelestaDefault: String
}

ColumnMeta <|.. ViewColumnMeta
ColumnMeta <|.. Column   

Column <|-l- IntegerColumn
Column <|-- FloatingColumn
Column <|-- StringColumn
Column <|-- BinaryColumn
Column <|-- DateTimeColumn
Column <|-- ZonedDateTimeColumn
Column <|-- DecimalColumn
Column <|-r- BooleanColumn
@enduml
----


== Методы модификации метаданных

Модификация метаданных во время выполнения возможна следующим образом:

[cols="1, 2, 2, 1, options="header"]
|====
^.^|Тип объекта
^.^|Методы добавления
^.^|Методы модификации
^.^|Метод удаления

|Гранула
|`Grain(score, name)` —
конструктор создаёт объект-гранулу
с именем `name`, привязанную к `score`.
|`setVersion(version)` —
устанавливает тэг версии (version tag).
|метод отсутствует,
гранула может быть удалена только
физическим удалением папки
с гранулой из Score.

|Таблица
|`Table(grain, name)` —
конструктор создаёт объект-таблицу
с именем name, привязанную к объекту-грануле `grain`.
|`setPK(columnName, ...)` —
устанавливает первичный ключ таблицы на основе переданного
массива имён столбцов. Попытка установки пустого
первичного ключа приводит к ошибке.
|`delete()` —
удаляет таблицу из гранулы

|Поле
|`BinaryColumn(table, name)`
`BooleanColumn(table, name)`
`DateTimeColumn(table, name)`
`ZonedDateTimeColumn(table, name)`
`FloatingColumn(table, name)`
`DecimalColumn(table, name, precision, scale)`
`IntegerColumn(table, name)`
`StringColumn(table, name)` —
создаёт поле нужного типа с именем `name`,
привязанное к объекту-таблице `table`.
|`setNullableAndDefault(nullable, defaultValue)` —
первый (булевский) аргумент этого метода управляет
свойством `isNull`, второй (строковый) — задаёт значение `DEFAULT`,
используя синтаксис соответствующего определения поля. Например,
для поля даты здесь допустимо использование слова `GETDATE`.
`setLength(length)` —
определён только для `StringColumn`,
устанавливает длину строки. Возможно использование
слова `MAX` в качестве длины.
`setPrecision(precision)` —
определён только для `DecimalColumn`,
устанавливает длину числа в символах.
`setScale(scale)` —
определён только для `DecimalColumn`,
устанавливает длину дробной части в символах.
|`delete()` —
удаляет поле из таблицы

|Внешний ключ
|`ForeignKey(parentTable, referencedTable, columnNames)` —
конструктор создаёт объект-внешний ключ,
привязанный к таблице `parentTable`, ссылающийся на
`referencedTable`. В массиве строк `columnNames`
передаётся список имён столбцов, с которых идёт ссылка.
|`setUpdateRule(updateRule)`
`setDeleteRule(deleteRule)` —
устанавливает поведение внешнего ключа на обновление
или удаление записи, на которую есть ссылка
(`SET NULL`, `CASCADE`, `NO_ACTION`). В качестве аргумента
следует передавать одно из значений перечисления {apidocs}ru/curs/celesta/score/FKRule.html[`FKRule`].
|`delete()` —
удаляет внешний ключ

|Индекс
|`Index(table, name, columnNames)` —
создаёт индекс на таблице `table` с именем `name` и списком
полей `columnNames`, передаваемом как массив строк.
|
|`delete()` —
удаляет индекс

|Представление
|`View(grain, name, sql)` —
создаёт представление в грануле `grain`, с именем `name`,
на основе sql-запроса `sql`.
|Для того, чтобы изменить sql-запрос, на основе которого
сделано представление, удалите существующее
представление и создайте новое с тем же именем.
`getCelestaQueryString()` — возвращает SQL-запрос представления
`getColumns()` — возвращает перечень имён столбцов представления
|`delete()` — удаляет представление

|====

У каждого класса-наследника {apidocs}ru/curs/celesta/score/NamedElement.html[`NamedElement`] имеются также методы `getCelestaDoc()` и `setCelestaDoc()` для чтения и установки документирующих данных CelestaDoc. При сохранении в файл динамически изменённых метаданных CelestaDoc-комментарии сохраняются.

//end::meta[]
