/* Generated By:JavaCC: Do not edit this line. CelestaParserConstants.java */
package ru.curs.celesta.score;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface CelestaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_ACTION = 5;
  /** RegularExpression Id. */
  int K_ADD = 6;
  /** RegularExpression Id. */
  int K_ALTER = 7;
  /** RegularExpression Id. */
  int K_AND = 8;
  /** RegularExpression Id. */
  int K_AS = 9;
  /** RegularExpression Id. */
  int K_BETWEEN = 10;
  /** RegularExpression Id. */
  int K_BY = 11;
  /** RegularExpression Id. */
  int K_CASCADE = 12;
  /** RegularExpression Id. */
  int K_CONSTRAINT = 13;
  /** RegularExpression Id. */
  int K_COUNT = 14;
  /** RegularExpression Id. */
  int K_CREATE = 15;
  /** RegularExpression Id. */
  int K_DEFAULT = 16;
  /** RegularExpression Id. */
  int K_DELETE = 17;
  /** RegularExpression Id. */
  int K_DISTINCT = 18;
  /** RegularExpression Id. */
  int K_FALSE = 19;
  /** RegularExpression Id. */
  int K_FOREIGN = 20;
  /** RegularExpression Id. */
  int K_FROM = 21;
  /** RegularExpression Id. */
  int K_FULL = 22;
  /** RegularExpression Id. */
  int K_GETDATE = 23;
  /** RegularExpression Id. */
  int K_GROUP = 24;
  /** RegularExpression Id. */
  int K_IDENTITY = 25;
  /** RegularExpression Id. */
  int K_IN = 26;
  /** RegularExpression Id. */
  int K_INDEX = 27;
  /** RegularExpression Id. */
  int K_INNER = 28;
  /** RegularExpression Id. */
  int K_IS = 29;
  /** RegularExpression Id. */
  int K_JOIN = 30;
  /** RegularExpression Id. */
  int K_KEY = 31;
  /** RegularExpression Id. */
  int K_LEFT = 32;
  /** RegularExpression Id. */
  int K_LIKE = 33;
  /** RegularExpression Id. */
  int K_MATERIALIZED = 34;
  /** RegularExpression Id. */
  int K_TABLE = 35;
  /** RegularExpression Id. */
  int K_VIEW = 36;
  /** RegularExpression Id. */
  int K_NOT = 37;
  /** RegularExpression Id. */
  int K_NULL = 38;
  /** RegularExpression Id. */
  int K_TEXT = 39;
  /** RegularExpression Id. */
  int K_PRIMARY = 40;
  /** RegularExpression Id. */
  int K_REFERENCES = 41;
  /** RegularExpression Id. */
  int K_ON = 42;
  /** RegularExpression Id. */
  int K_UPDATE = 43;
  /** RegularExpression Id. */
  int K_NO = 44;
  /** RegularExpression Id. */
  int K_SET = 45;
  /** RegularExpression Id. */
  int K_OR = 46;
  /** RegularExpression Id. */
  int K_SELECT = 47;
  /** RegularExpression Id. */
  int K_RIGHT = 48;
  /** RegularExpression Id. */
  int K_WHERE = 49;
  /** RegularExpression Id. */
  int K_TRUE = 50;
  /** RegularExpression Id. */
  int K_SUM = 51;
  /** RegularExpression Id. */
  int K_MIN = 52;
  /** RegularExpression Id. */
  int K_MAX = 53;
  /** RegularExpression Id. */
  int K_INT = 54;
  /** RegularExpression Id. */
  int K_REAL = 55;
  /** RegularExpression Id. */
  int K_VARCHAR = 56;
  /** RegularExpression Id. */
  int K_BLOB = 57;
  /** RegularExpression Id. */
  int K_DATETIME = 58;
  /** RegularExpression Id. */
  int K_BIT = 59;
  /** RegularExpression Id. */
  int S_DOUBLE = 60;
  /** RegularExpression Id. */
  int S_INTEGER = 61;
  /** RegularExpression Id. */
  int DIGIT = 62;
  /** RegularExpression Id. */
  int S_BINARY_LITERAL = 63;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 64;
  /** RegularExpression Id. */
  int LETTER = 65;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 66;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 67;
  /** RegularExpression Id. */
  int CELESTA_DOC = 68;
  /** RegularExpression Id. */
  int LINE_COMMENT = 69;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 70;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"ACTION\"",
    "\"ADD\"",
    "\"ALTER\"",
    "\"AND\"",
    "\"AS\"",
    "\"BETWEEN\"",
    "\"BY\"",
    "\"CASCADE\"",
    "\"CONSTRAINT\"",
    "\"COUNT\"",
    "\"CREATE\"",
    "\"DEFAULT\"",
    "\"DELETE\"",
    "\"DISTINCT\"",
    "\"FALSE\"",
    "\"FOREIGN\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"GETDATE\"",
    "\"GROUP\"",
    "\"IDENTITY\"",
    "\"IN\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"IS\"",
    "\"JOIN\"",
    "\"KEY\"",
    "\"LEFT\"",
    "\"LIKE\"",
    "\"MATERIALIZED\"",
    "\"TABLE\"",
    "\"VIEW\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"TEXT\"",
    "\"PRIMARY\"",
    "\"REFERENCES\"",
    "\"ON\"",
    "\"UPDATE\"",
    "\"NO\"",
    "\"SET\"",
    "\"OR\"",
    "\"SELECT\"",
    "\"RIGHT\"",
    "\"WHERE\"",
    "\"TRUE\"",
    "\"SUM\"",
    "\"MIN\"",
    "\"MAX\"",
    "\"INT\"",
    "\"REAL\"",
    "\"VARCHAR\"",
    "\"BLOB\"",
    "\"DATETIME\"",
    "\"BIT\"",
    "<S_DOUBLE>",
    "<S_INTEGER>",
    "<DIGIT>",
    "<S_BINARY_LITERAL>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<CELESTA_DOC>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\";\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"-\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"+\"",
    "\"||\"",
    "\"*\"",
    "\"/\"",
  };

}
