CREATE GRAIN test2 VERSION '2.0';

-- *** TABLES ***
CREATE TABLE c(
  iii INT NOT NULL IDENTITY,
  bbb NVARCHAR(2),
  sss INT
  PRIMARY KEY (iii);
);

CREATE TABLE d(
  e NVARCHAR(5) NOT NULL DEFAULT '-'
  PRIMARY KEY (e);
);

CREATE TABLE a(
  a INT NOT NULL DEFAULT 0,
  b NVARCHAR(5) NOT NULL DEFAULT '',
  c DATETIME,
  d INT,
  kk NVARCHAR(5)
  PRIMARY KEY (a, b);
);

CREATE TABLE b(
  a NVARCHAR(5) NOT NULL DEFAULT '',
  b INT,
  c INT
  PRIMARY KEY (a);
);

-- *** FOREIGN KEYS ***
ALTER TABLE a ADD CONSTRAINT fk1 FOREIGN KEY (kk) REFERENCES d(e) ON UPDATE SET NULL;
ALTER TABLE a ADD CONSTRAINT fk2 FOREIGN KEY (d) REFERENCES c(iii);
ALTER TABLE b ADD CONSTRAINT fk3 FOREIGN KEY (b, a) REFERENCES a(a, b) ON UPDATE CASCADE ON DELETE CASCADE;
-- *** INDICES ***
