# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          
      - name: Set up JDK11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          targets: 'JDK_11'
          
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Install apell and graphviz
        run: sudo apt-get install -y aspell-en aspell-ru graphviz
      - name: Install jsyntrax
        run: |
          wget https://github.com/atp-mipt/jsyntrax/releases/download/1.1/jsyntrax-1.1-syntrax.zip -nv -O jsyntrax.zip
          unzip -q jsyntrax.zip
          rm jsyntrax.zip
          sudo chmod +x $(pwd)/jsyntrax-1.1/bin/syntrax
          sudo ln -s $(pwd)/jsyntrax-1.1/bin/syntrax /usr/local/bin/syntrax
          JAVA_HOME=$JDK_11; syntrax --version
      
      - name: Spellcheck
        run: |
          chmod +x spellcheck 
          ./spellcheck en
          ./spellcheck ru
      
      - name: Build Javadoc
        run: mvn javadoc:aggregate -pl :celesta-parent,:celesta-sql,:celesta-core,:celesta-system-services,:celesta-unit
      - name: Build documentation
        run: JAVA_HOME=$JDK_11; mvn generate-resources -pl :celesta-documentation       
      - name: Move Javadoc
        run: mv target/site/apidocs celesta-documentation/target/generated-docs/apidocs
      - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/dev'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: celesta-documentation/target/generated-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
