name: Build and Upload Generated Sources

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Java 11 (Temurin)
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Run Maven javac goal
        run: mvn javac:javac

      - name: Zip generated sources
        run: |
          zip -r generated-sources.zip elesta-core/target/generated-sources

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: generated-sources
          path: generated-sources.zip
