name: build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      
      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}

      - name: Build and test Celesta
        run: mvn verify -P dev -pl !celesta-documentation

      - name: Publish test report
        uses: dorny/test-reporter@v1
        if: success() || failure()    
        with:
          name: Test report          
          path: '**/surefire-reports/**/*.xml'    
          reporter: java-junit

      - name: Publish test coverage
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-coverage
          path: coverage-report/target/site/jacoco-aggregate
